### ISSUE TITLE
Explanation for id_property metaprogramming

### ISSUE THREAD

**Issue by venkatd** [neo4jrb/neo4j#1002]
Hey all. I'm having an issue in my project where calling `id_property :uuid`, then requiring that model somewhere (like rails console or rake) gives me a stack level too deep error. I don't get this error when an `auto` or `on` option is passed in.

Was wondering if someone would be able to explain the metaprogramming going on below in id_property.rb:
```ruby
      def define_id_methods(clazz, name, conf)
        validate_conf!(conf)

        if conf[:on]
          define_custom_method(clazz, name, conf[:on])
        elsif conf[:auto]
          define_uuid_method(clazz, name)
        elsif conf.empty?
          define_property_method(clazz, name)
        end
      end

      def define_property_method(clazz, name)
        clear_methods(clazz, name)

        clazz.module_eval(%(
          def id
            _persisted_obj ? #{name.to_sym == :id ? 'attribute(\'id\')' : name} : nil
          end

          property :#{name}
                ), __FILE__, __LINE__)
      end


      def define_uuid_method(clazz, name)
        clear_methods(clazz, name)

        clazz.module_eval(%(
          default_property :#{name} do
             ::SecureRandom.uuid
          end

          def #{name}
             default_property_value
          end

          alias_method :id, :#{name}
                ), __FILE__, __LINE__)
      end

      def define_custom_method(clazz, name, on)
        clear_methods(clazz, name)

        clazz.module_eval(%{
          default_property :#{name} do |instance|
            raise "Specifying custom id_property #{name} on non-existent method #{on}" unless instance.respond_to?(:#{on})
            instance.#{on}
          end

          def #{name}
            default_property_value
          end

          alias_method :id, :#{name}
        }, __FILE__, __LINE__)
      end
```

Also I wonder if the string eval is necessary. Could we use `class_eval` and write regular ruby instead?

**Comment by subvertallchris** [comment]
Yeah, there's a lot happening in there. I can help you but I have a bit of a backlog piling up today, so a detailed convo might have to wait until this afternoon. In the meantime, I can try to explain its logic and outcome.

The `id_property` method should be the only public method in this interface. Its options trigger the branching logic in `define_id_methods`. There are three paths it can take but I'm going to present it as two:

* Both `auto: :uuid` and `on: :method_name` define a basic _getter_ for the id property but do not give an explicit setter or officially declare a property with the `property` method. Instead, they rely on `default_property` to set the values. It returns a hash with the format `{ property_name: proc_that_returns_value_to_use }`.

* When given without options, `property` is invoked and that key is set as the model's id property/primary key, but it contains no logic or requirement for setting the value.

As for why it's written like this, I couldn't say. I don't think this code has had much attention since it went into the gem last year. If you want to take a stab at refactoring, we'd definitely welcome a PR.

**Comment by subvertallchris** [comment]
BTW, feel free to pop into our Gitter room, https://gitter.im/neo4jrb/neo4j, any time. I'm logged in all day and Brian's around all night while he's in East Asia, so we pretty much have 24-hour coverage ATM. We have a small crew hanging out, too. The room in neo4j-users.slack.com is also very active.

**Comment by venkatd** [comment]
Thanks for the explanation! I've got some travel time this coming month so happy to take a stab at refactoring some of the meta-programming.

My philosophy is to keep the meta-programming to a minimum when the code saved really outweighs the added complexity. I'll pick your brain on exactly how you want `:uuid` to behave.

I see a few cases:
```ruby
class User
    id_property :uuid
end
```

```ruby
class User
    id_property :uuid, auto: :uuid
end
```

```ruby
class User
    id_property :uuid, on: :my_custom_method
end
```

And then of course there's the case where `:uuid` is instead a column such as `:my_uuid`. I'll try to write down an example of what each call ends up generating.

**Comment by cheerfulstoic** [comment]
That seems right, though I would point out that what happens the majority of the time is that no `id_property` is specified and the default chosen is `uuid` with `SecureRandom.uuid` as the default ID generator.  I seem to remember that code being a bit tricky because you basically have to wait until the session is open or when a user queries (I forgot which) to determine that no `id_property` has been specified.

It might be nice to have a "class has finished loading" hook, though that doesn't seem to exist.  That said, though, sometimes people might re-open the class to define more things and so I don't think that would be a good place to define the default `id_property` anyway

**Comment by venkatd** [comment]
Don't have a need for this at the moment so I will revisit. Closing for now. Thanks guys!
