### ISSUE TITLE
Trouble running in test mode

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#1064]
I downloaded two days ago the latest version Of neo4j and neo4jrb.
Then I  made the required changes to upgrade from rake start to /bin/neo4j start
It runs fine in dev stage.
Then I just cloned my dev machine to create a new dedicated test machine.
Neo4j started, but rails cannot connect with it if started with -etest

Is there any work to do to tell Neo4j to run in test?

Also, By your experience, in production stage, it is better to run both neo4j and rails in background?

Have you got some samples of the recent configuration file for the three different stages?

Paolo

**Comment by cheerfulstoic** [comment]
So there's nothing test-specific about Neo4j.  You generally just need to have multiple instances of Neo4j set up on different ports.  The [Rake Tasks](http://neo4jrb.readthedocs.org/en/6.0.x/RakeTasks.html) can help you with this by making it easy to have different instances of Neo4j in different directories within your Rails app by specifying different environments and also by letting you configure the ports with a rake task.  All of this comes from the `neo4j-rake_tasks` gem.  You could also use something like [ineo](https://github.com/cohesivestack/ineo) or just manage the instances yourself.

One caution though: If you use the rake tasks to set up your Neo4j instance on production it may disable credentials (because we do that in development and test to make things simpler).  That is not advised for production

In Rails, the only thing that you should need to do is have the Rails environment set to `test`.  This is generally done automatically in your `(test|spec|whatever)_helper.rb`.  You should also make sure that the right URL / port is configured differently for the different environments.  That can either be done via `config/neo4j.yml` in the latest version of the gems or via the `config/environments/(development|test).rb` files.  That's all laid out here:

http://neo4jrb.readthedocs.org/en/6.0.x/Setup.html#ruby-on-rails

Here's an example app that I've been making recently that is open source and that has specs:

https://github.com/neo4j-examples/graphgist_portal

I'm going to close this issue since I don't think it involves a bug or a feature for the gem, but feel free to [open a StackOverflow issue](http://stackoverflow.com/questions/ask?tags=neo4j.rb+neo4j+ruby) if you're still having problems
