### ISSUE TITLE
`find` should keep track of the current scope

### ISSUE THREAD

**Issue by ProGM** [neo4jrb/neo4j#1120]
In ActiveRecord if I do:

```ruby
class Article < ActiveRecord::Base
  scope :draft, -> { where(published: false) }
end
a = Article.create(published: false)
Article.draft.find(a.id) # => ActiveRecord::RecordNotFound
```

In Neo4j instead:

```ruby
class Article
  include Neo4j::ActiveNode
  scope :draft, -> { where(published: false) }
end
a = Article.create(published: false)
Article.draft.find(a.id) # => <# Article id: ...>
```

It seems that `find` is ignoring the current scopes. Is it a bug?

**Comment by cheerfulstoic** [comment]
Ah, yes, that definitely seems like a bug.  We should fix that.  Can you share the Cypher that's being generated?  If you're not in Rails you can see the Cypher by running the following before executing the queries:

```ruby
Neo4j::Server::CypherSession.log_with {|message| puts message }
```

**Comment by ProGM** [comment]
Using `Article.draft.find(uuid)`:
```cypher
MATCH (result_version:`Article`) WHERE (result_version.uuid = {result_version_uuid}) RETURN result_version ORDER BY result_version.uuid LIMIT {limit_1}
```
This does not happens if I use `Article.draft.find_by(uuid: something)`. Example:

```cypher
MATCH (n:`Article`) WHERE (n.published = {n_published}) AND (n.uuid = {n_uuid}) RETURN n LIMIT {limit_1}
```

**Comment by subvertallchris** [comment]
We need to get rid of that `ORDER BY whatever.uuid`, too.

**Comment by cheerfulstoic** [comment]
Ok @ProGM I think that this is fixed in the `6.1.x` branch.  You can give it a try by using this in your `Gemfile`:

```ruby
gem 'neo4j', github: 'neo4jrb/neo4j', branch: '6.1.x'
```

It's running on Travis CI now, but when it passes I'll cut a new patch release.

**Comment by cheerfulstoic** [comment]
I'm not as sure about getting rid of the `ORDER BY`...  It matches the way that `ActiveRecord` works.  Though I understand it's a weird case because Neo4j doesn't do the `ORDER BY` well for millions of records for the label.

Normally I don't like configuration options for fiddly things, but what about making a configuration option to disable this behavior?

**Comment by cheerfulstoic** [comment]
Just released 6.1.5 with a fix for this.  Give it a try!

**Comment by ProGM** [comment]
Great! I'm upgrading!

About `ORDER BY uuid`: In ActiveRecord, an id is an increasing value, where the bigger is (in general) the most recent. `uuid` doesn't have the same meaning, right?

**Comment by cheerfulstoic** [comment]
Ah, yeah, I suppose that's true.  If we order I suppose we should order by `ID()`, but that doesn't have the same meaning as SQL auto-incrementing keys because they can be recycled.  So maybe we should drop it... Hrmm...

**Comment by subvertallchris** [comment]
That's what I was getting at. Ordering by UUID doesn't offer anything. Even
ordering by ID() is questionable since they can be reused, but it'd be a
start.

**Comment by cheerfulstoic** [comment]
Thought process in my head:

"But while UUID doesn't offer the order that you created objects it does offer a consistent ordering"
"Oh, right, but since it's random a new record could go anywhere in the order..."

I think I'm down with this, but I worry about `first` and `last` returning different results at different times.  Maybe that's true now, though...
