### ISSUE TITLE
Strange behavior with serialized property

### ISSUE THREAD

**Issue by DSIW** [neo4jrb/neo4j#1152]
```ruby
class Site
  include Neo4j::ActiveNode
  property :myids, default: []
  serialize :myids
  property :name, type: String, index: :exact
end

Site.delete_all

site = Site.find_or_create(name: "Example")
site.myids ||= []
site.myids << "2"
site.myids << "3"
site.save
Site.first #=> #<Site myids: [], name: "Example">
```

Why is myids empty? It works if I remove option `:default` from property `myids` and then it doesn't work if I rename `myids` to `ids`.

**Comment by cheerfulstoic** [comment]
Unfortunately this is a problem that we share with ActiveRecord ;(

In Ruby when you modify an array with `<<` there's no way (as far as I know) to tell that the array has changed (because it's the same object, but the contents have changed).  This means that our "dirty" tracking doesn't see the change and that when you call `save` no update is actually happening (because we only send down properties that have changed).

There are a couple of ways that you can work around this:

```ruby
site.myids += ["2"] # Assignment creates a new object and thus triggers dirty tracking

# or

site.myids_will_change! # Notify `ActiveNode` that this property has changed so that it will save
```

Does that work for you?

**Comment by DSIW** [comment]
Thank's for your quick response. That works! :+1:

**Comment by cheerfulstoic** [comment]
Glad to hear it! :+1:
