### ISSUE TITLE
Expose identity variable for string-based Query calls

### ISSUE THREAD

**Issue by brucek** [neo4jrb/neo4j#1158]
Right now there are 2 ways to set up a scope that uses a string query and 

```ruby
Student.scope :in_order, -> (student) { order("#{student}.level_num DESC") }
Student.query_as(:student).in_order(:student)
```
or
```ruby
Student.scope :in_order, -> { order("#{@query_proxy.identity}.level_num DESC") }
Student.in_order
```

The second method is much nicer, but you need some magic knowledge of the `Neo4j::ActiveNode::Scope::ScopeEvalContext` internals.  It would be nice to wrap the @query_proxy.identity as just identity, so this would work:

```ruby
Student.scope :in_order, -> { order("#{identity}.level_num DESC") }
Student.in_order
```

...which I saw @subvertallchris [mention in chat](https://gitter.im/neo4jrb/neo4j?at=54e106b46060c9ab047f12fe) but it didn't seem to work, so I added it in.

Does this make sense to expose here?  Or did I miss some other idiomatic way to do this somewhere?

**Comment by cheerfulstoic** [comment]
Firstly, I'm a bit confused by:

```ruby
Student.query_as(:student).in_order(:student)
```

The `in_order` shouldn't be available to a `Query` object.  Did you mean `as` instead of `query_as`?

So I think this is a very good idea, though in your particular case I think you should be able to do:

```ruby
Student.scope :in_order, -> { order(level_num: :desc) }
```

This sort of goes to the `Query` syntax for `order`:

http://neo4jrb.readthedocs.org/en/6.1.x/QueryClauseMethods.html#order

When you pass in a hash to `order` for a `QueryProxy` it will basically just pass it on down into the `Query` with `identity => argument`

**Comment by brucek** [comment]
hey, thanks for the comments:

1.  yes that should be `as` instead of `query_as`

2.  Yeah, my actual case I need this for looks like:

```ruby
scope :alpha_sorted, -> { order("coalesce(#{@query_proxy.identity}.display_name, #{@query_proxy.identity}.imported_name)") }
```

...but I was trying to stay with the existing doc conventions.  Let me try & make a better example (basically anything that needs a CYPHER function)

**Comment by cheerfulstoic** [comment]
Ah, yeah, that would definitely need the identity ;)

Great, I'm happy then with the doc changes

**Comment by brucek** [comment]
as a side comment I haven't actually taken the time to parse out when `as` vs `query_as` will/won't work, I was looking at this which seems [hella confusing](https://github.com/neo4jrb/neo4j/wiki/Search-and-Match#detailed-querying)

**Comment by cheerfulstoic** [comment]
Very good point, we should provide better docs for that.  For you and anybody else reading:

`query_as` is just a way to turn a `QueryProxy` (or `AssociationProxy`, but really `AssociationProxy` is just a wrapper for `QueryProxy`) into a `Query` object.  The `Query` object chaining API is a way to build raw Cypher queries using Ruby like so:

```ruby
Neo4j::Session.current.query.match('(n:Foo)-[r]-(m:Bar)').where(m: {name: 'Baz'}).return(:n)
```

`Query` objects can be simply have `exec` called on them, but they're also `Enumerable` and so they'll enumerate over objects that contain whatever you've specified in your one or more `return` calls.  Of course you can also do `pluck` instead of return which will immediately return a 2D array.

`Query` chains can sometimes be overkill for certain queries, but they have a number of advantages:

 * Uses parameters wherever it can
 * Allows you to pass along `Query` objects part-way through and continue building them in different contexts
 * Sometimes allows you to build your queries with Ruby data without you needing to generate your own Cypher queries

And, of course, the entire `ActiveNode` association chaining / `QueryProxy` functionality uses them under the covers.

`as`, on the other hand, is just a way to turn a model class into a `QueryProxy` chain so that you can set the `identity`.  Like:

```ruby
Model.as(:var)
```

You only need to use that if you need to refer to the nodes for that model later.

I would actually like to replace the `association(:node_var, :rel_var)` syntax with `association.as(:node_var, :rel_var)`.  There are some issues where we discuss how to go about it, but it would simplify our code a lot and I don't *think* it would cause too much of a transition for users of the gem.

**Comment by brucek** [comment]
Thanks for that explanation.  I'm going to ask the naive questions here, and I'll leave it to you to determine whether I am actually naive or just playing the part ;-)

So as a beginning user, what I would ideally want is a single syntax (`as`/`query_as`/etc) that I can use anywhere in the chain to get a handle to the identity, regardless of whether I am calling it on the `Model`, `Query`, `Query Proxy`, etc.

I think this is what your last paragraph is saying?  So we can just use `as` everywhere in the chain (`Model` or no)?

On a related topic, I have gotten this far without really understanding the difference at the `neo4jrb` dev user level between having an `AssociationProxy`/`QueryProxy` and having an actual `Query` object.

I say this because from my standpoint, I just want to build a neo4j query and get some results.  I start with a model (or instance), and call a set of methods against it.  Which layers those methods come from would ideally be opaque to me, so they would be smart enough to know when to convert into `Query` objects (or not), to convert back if/when needed, etc.

You can argue that I *should* know what's going on, but as someone who just wants to Get Things Done, I'd ideally want to make it unnecessary unless I'm doing something weirdly out of the ordinary.

Of course, I am discounting all the work required to make that happen (and thank you again for all your work and support on this project so far as well - you guys are super helpful, friendly & responsive, which I really appreciate).

Anyways, since I am coming at it with Beginner's Mind, I thought maybe some questions from here might be helpful to you or others reading along at home.  Thanks again.

**Comment by cheerfulstoic** [comment]
Yes, I absolutely think that as much as possible you shouldn't have to care about the underlying implementation and just care about the syntax / API. This is something that I've seen confuse people and I would like to make as smooth as possible.  I definitely welcome your Beginner's Mind to the process ;)

When people start using the gem they can largely be in the "association-chaining" world.  This is the world of `AssociationProxy` / `QueryProxy`, but I try to avoid calling it that as much as I can.  That particular API lets you go a ways without needing to understand too much other than what the syntax is.  I would like to offer more higher-level features where it makes sense, though.  For example until `7.0.0` it was hard to create anything other than a linear association chain using just association chaining.  

If, for example, I wanted to find all of the comments on posts for a user, but limit by certain tags for the post I would need to do something like:

```ruby
# `special_tags` is a hypothetical scope in this case
user.posts(:post).tags.special_tags.query.proxy_as(Post, :post).comments
```

In 7.0.0 you can now use the `branch` method:

```ruby
user.posts.branch { tags.special_tags }.comments
```

This is a great addition which lets users to accomplish more complex things at a higher level without needing to understand Cypher too much.

So part of our goal with the gem has been to make it so that people can have this easy path into Neo4j and then start using Cypher where it makes sense.  Cypher is a very powerful language and I think there are things that are probably never going to be replicatable at a higher level.  Because of that I think that there's always going to need to be this separate API that users can drop down to when they need more control.

I think a good documentation page on the subject would be a big step forward in making this learning path easier for beginners.  We definitely welcome other suggestions (and confusions).

Separately, as to `as`:

What I was saying is that I wished you would use `as` to label your variables throughout your association chain.  Currently, though, it's just for labeling the variables for a model to start a query based on all nodes for that model:

```ruby
User.posts # user nodes aren't given a variable
User.as(:user).posts # users are given a variable
```

I would like to see the variable made available throughout like so:

```ruby
# The syntax
user.posts.as(:post, :rel_var).comments.author.as(:comment_author)
# `rel_var` is the variable between users and posts

# The current syntax
user.posts(:post).comments.author(:comment_author)
```

I think I actually was working on a branch for that feature but it fell by the wayside
