### ISSUE TITLE
please support rails5  thanks !

### ISSUE THREAD

**Issue by FingersKey** [neo4jrb/neo4j#1198]
Additional information which could be helpful if relevent to your issue:

### Runtime information:

Neo4j database version:
`neo4j` gem version: 
`neo4j-core` gem version:

**Comment by cheerfulstoic** [comment]
If you have a particular error that you're getting that would be much more useful than just asking for Rails 5 support.

Also, closing because there is already [this PR](https://github.com/neo4jrb/neo4j/pull/1185).  I'd suggest trying `agustinvinao`'s branch to see if it fixes any problems that you might be having first:

```ruby
gem 'neo4j', github: 'agustinvinao/neo4j', branch: 'rails5'
```

**Comment by FingersKey** [comment]
thanks!

**Comment by cheerfulstoic** [comment]
Quick update, @subvertallchris is working on taking the changes that we have for a `7.1.0` which will put out all of the fixes that we have for rails5 so far.
