### ISSUE TITLE
How to create a relational index?  

### ISSUE THREAD

**Issue by FingersKey** [neo4jrb/neo4j#1201]

**Comment by cheerfulstoic** [comment]
Neo4j has legacy indexes which allow you to do this, though the gems don't support legacy indexes currently.  Normally it's encouraged to start your queries with nodes instead of indexes, so I'd be curious to know what you're trying to model.

You're also welcome to join us on [Gitter](https://gitter.im/neo4jrb/neo4j) or the [public Neo4j Slack group](http://neo4j.com/blog/public-neo4j-users-slack-group/)

**Comment by FingersKey** [comment]
FamilyTree   50000 nodes

**Comment by cheerfulstoic** [comment]
That doesn't really help...  Why do you want a relationship index?

**Comment by FingersKey** [comment]
the model is like this,i want to find all the nodes which belongs to the "belongs_to" relation 

![12333](https://cloud.githubusercontent.com/assets/15059533/15285827/4120f6b8-1b8c-11e6-8be3-6e8005732f4d.jpg)

**Comment by FingersKey** [comment]
I got a query solution , but it didn't work well. Actually it's acts very slow.

**Comment by cheerfulstoic** [comment]
I'd suggest either joining the [Neo4j Slack Group](http://neo4j.com/blog/public-neo4j-users-slack-group/) or posting a question to [StackOverflow](http://stackoverflow.com/questions/ask?tags=neo4j.rb+neo4j+ruby) to see if you can find a more efficient way to query and/or a better way to model your data.

I'd also suggest trying out the `EXPLAIN` / `PROFILE` documented [here](http://neo4j.com/docs/stable/how-do-i-profile-a-query.html).  I'd also learn about [execution plans](http://neo4j.com/docs/stable/execution-plans.html).

```cypher
PROFILE MATCH (g)-[:belongs_to]->(n:Individual)
WHERE ID(g) = 18265
RETURN g, n LIMIT 25
```

I don't think that this is something that is specific to Neo4j.rb (at least not yet), so I'm going to close this issue.
