### ISSUE TITLE
Add better support for undeclared properties

### ISSUE THREAD

**Issue by slnovak** [neo4jrb/neo4j#1209]
Hi,

First off -- thanks for this awesome gem! I'm currently looking into representing the [PROV](https://www.w3.org/TR/2013/REC-prov-dm-20130430/) model in a Rails via this gem.

I have a use case where I would like to have better support for undeclared properties. Given that they can be accessed via `_persisted_obj.props`, I imagine that it would be trivial to implement read-access via aliasing `post.properties` or `post.undeclared_properties` to that method.

Additionally, it would be great to support undeclared properties on `create`, I.e., `Post.create(title: "Foo", undeclared_properties: {foo: 1, bar: 2})`. In this case, `foo` and `bar` would not be accessible on the newly create object, but would only be accessible via `undeclared_properties`.

Please let me know what your thoughts are on this.

Cheers!

**Comment by cheerfulstoic** [comment]
I think that this could be a good idea, though I have a couple of questions first:

 * Are you trying to store dynamic properties which you won't know, necessarily, when you're building your code?
 * If so, would one or more [serialization](http://neo4jrb.readthedocs.io/en/v7.0.0/ActiveNode.html#serialization) property be an option for you?

**Comment by slnovak** [comment]
Hi @cheerfulstoic,

Thanks for getting back! Yes to the first question and no to the second.

Just a bit of background: I'm interested in implementing W3C's [PROV data model](https://www.w3.org/TR/2013/REC-prov-dm-20130430/) as a Rails application via Neo4j to track provenance for various data workflows. There are times where I want to attach additional data to nodes and query across them.

Currently, I'm working around this by implementing the method:

```ruby
  def update_properties(**props)
    neo4j_obj.update_props(props)
    self
  end
```

to attach additional properties to the node. Granted these properties aren't directly query-able via ActiveNode attributes, it should still be searchable via `.where`.

Do you see any other useful applications of supporting this functionality?

Thanks!

**Comment by cheerfulstoic** [comment]
Ah, yes, of course ;)  I didn't think about the fact that you might want to filter on them.

Yeah, I think you solution would be good for addressing that and I like your ideas.  The one open question I have: I would also like to, at some point, have the functionality that when querying for nodes you can specify the properties that you want to load so that you don't have to load everything over the wire.  I still don't know how exactly that might work (maybe the `properties` / `undeclared_properties` hashes would only be partially filled and we might have some method that you could call to tell what properties were requested for loading that node).

Another thought, though: What about dynamically calling the `property` class method when you're going to need a property?  This would also give you the ability to add indexes too because sometimes if you're going to be filtering by the property an index can be important.  Though Neo4j also doesn't allow you to make schema changes (indexes/constraints) in the same transaction as data changes, so you might need to be careful about that.

**Comment by ProGM** [comment]
@slnovak I haven't read the entire discussion, but I think that this PR #1294 can be somehow related to it ;)
I think we'll release it soon in 8.x versions

**Comment by slnovak** [comment]
@ProGM: Wohoo! That's what I was looking for. Thanks!!
