### ISSUE TITLE
`neo4j:migrate` task is not creating a session (and not initializing the app)

### ISSUE THREAD

**Issue by ProGM** [neo4jrb/neo4j#1210]
If I run:

```bash
$ bin/rake neo4j:migrate
```

I get this error:
```bash
rake aborted!
No session, please create a session first with Neo4j::Session.open(:server_db) or :embedded_db

Tasks: TOP => neo4j:migrate:all
(See full trace by running task with --trace)
```

Instead if I run this:

```bash
$ bin/rake db:migrate neo4j:migrate
```

The migration runs correctly. I think that the rake task is not initializing the environment.

### Runtime information:

Neo4j database version:
`neo4j` gem version: 7.0.8
`neo4j-core` gem version: 6.0.4

**Comment by cheerfulstoic** [comment]
My guess is that `db:migrate` is loading the Rails environment and thus the `railtie.rb`.  The `legacy_migrate` seems to load the environment like this:

https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/tasks/migration.rake#L5

But would that work outside of Rails?  Could we use a generic way to open the session?  Maybe the code from `railtie.rb` should be extracted and simply called from `railtie.rb` and then we could also call it from things like these `rake` tasks or give people the option of using it manually so that they could just get things like `config/neo4j.yml` etc... for free

**Comment by ProGM** [comment]
Good idea! Maybe I can take a look ;)

**Comment by cheerfulstoic** [comment]
By all means! ;)

**Comment by ProGM** [comment]
Closing here ;)
