### ISSUE TITLE
Constraint initialization does not honor mapped_label_name

### ISSUE THREAD

**Issue by leviwilson** [neo4jrb/neo4j#1214]
### Problem
Since constraints are evaluated when you `include Neo4j::ActiveNode`, the incorrect constraints are applied for the `uuid` property.

```ruby
module A
  module B
    class Thing
      include Neo4j::ActiveNode
      self.mapped_label_name = :ThingUnderB

      property :value, type: String, constraint: :unique
    end
  end
end
```

When this model is loaded for the first time, you will see the following output:

```sql
 CYPHER 23ms CREATE CONSTRAINT ON (n:`A::B::Thing`) ASSERT n.`uuid` IS UNIQUE 
 CYPHER 18ms CREATE CONSTRAINT ON (n:`ThingUnderB`) ASSERT n.`value` IS UNIQUE 
```

### Ideas
I'm wondering if it would make sense to handle the modification of the constraints (for the `uuid`) whenever `:mapped_label_name=` is called. I'm not sure if there's a way to get the inclusion of `Neo4j::ActiveNode` to _not_ create the initial constraint; so if that's not possible if it can drop the default constraint name (based on the full, modularized name of the class i.e. `"A::B::Thing"`) and set it correctly for `:ThingUnderB` whenever you override it. Thoughts?

### Runtime information:

Neo4j database version:
`neo4j` gem version: `7.0.6`
`neo4j-core` gem version: `6.1.4`

**Comment by subvertallchris** [comment]
Surprised to say I just discovered that you can work around this by defining the method before you include the module.

```ruby
module A
  module B
    class Thing
      def self.mapped_label_name
      	:ThingUnderB
      end

      include Neo4j::ActiveNode

      property :value, type: String, constraint: :unique
    end
  end
end
```

Something something eigenclass. Is this THE solution? How do we test it to document this behavior, since this comes up all the time?

**Comment by leviwilson** [comment]
Yes, that _works_...I'm guessing because when ActiveSupport mixes in stuff from [`Neo4j::ActiveNode::Labels` here](https://github.com/neo4jrb/neo4j/blob/39456bf782f5a4fdb58f2108110e64837750c1ac/lib/neo4j/active_node/labels.rb#L124) that it doesn't use the original definition?

What did you think about the approach I was saying by doing more in the `:mapped_label_name=` method? That _feels_ like it would be more consistent with how they work when you do `property :blah, constraint: :unique`, since that honors the `self.mapped_class_name = :ThingUnderB`.

**Comment by subvertallchris** [comment]
When using `ActiveSupport::Concern` and `ClassMethods` modules to create class methods, methods defined explicitly in the class will always be called instead of methods defined in the body of `ClassMethods`. I'm not sure if this is deliberate or a happy coincidence but it's pretty interesting to see it in action.

The issue with relying on `mapped_label_name=` is that by the time it's called, the defaults are already set. Setting and unsetting extra constraints on the default label value is something we need to avoid entirely. I think we're going to need to either move away from doing any schema stuff on the inclusion of ActiveNode or provide some basic config externally (a YML file with mappings of Ruby class to correct label?) or in the code before ActiveNode is included. I'm not sure that my workaround is the best solution because it's sort of a happy coincidence.

As a radical option, we could consider moving from `include Neo4j::ActiveNode` to `include Neo4j::ActiveNode.new(config_params)` as demonstrated [here](https://medium.com/@eric.programmer/arguments-for-included-modules-in-ruby-8056b9fa2743) but that would be a huge breaking change for literally everyone. I'm not a huge fan of this.

**Comment by subvertallchris** [comment]
Ahh, I see now that you're pointing out that it wasn't setting the id property constraint _at all_ after changing the mapped_label_name. So, yes, you're right, it does make sense to call the method again to fix things if id_property has already been set.

That's cool and a quick solution to the big problem of the missing constraint, but we really need a solution for the fact that undesired changes to the database are being made in the first place. I think we're going to need to either move away from doing any schema stuff on the inclusion of ActiveNode or provide some basic config externally (a YML file with mappings of Ruby class to correct label?) or in the code before ActiveNode is included. As long as we use 

As a radical option, we could consider moving from `include Neo4j::ActiveNode` to `include Neo4j::ActiveNode.new(config_params)` as demonstrated [here](https://medium.com/@eric.programmer/arguments-for-included-modules-in-ruby-8056b9fa2743) but that would be a huge breaking change for literally everyone. I'm not a huge fan of this.

**Comment by cheerfulstoic** [comment]
In the same line as my comment on your PR, in `new_cypher_api` I actually changed it so that we don't process the `id_property` for the constraint until the `id_property_info` is requested.  That should be the last possible moment.  To avoid breaking because of mixed schema/data changes, I also made schema changes happen inside of a thread in a separate transaction.

**Comment by subvertallchris** [comment]
👍 I like that!

**Comment by leviwilson** [comment]
_Soooooo_ imma close this one since eventually we'll have something moar nicer. I can work around the issue for now; thanks!
