### ISSUE TITLE
Implement rake neo4j:schema:load

### ISSUE THREAD

**Issue by ProGM** [neo4jrb/neo4j#1262]
We are implementing the entire AR migration API, so many people would expect to find an equivalent of `db:schema:load` ;)

**Comment by cheerfulstoic** [comment]
I was talking about implementing a schema file, but it would make much more sense to simply make it work like AR.  The biggest difference is that "schema" in Neo4j is indexes/constraints whereas SQL also contains tables/columns (more?).  Because of that I wonder if we should go the DSL route of ActiveRecord or just use `yml` / `json` / whatev

**Comment by cheerfulstoic** [comment]
Done
