### ISSUE TITLE
update record with `before_` hook raise RecordInvalidError

### ISSUE THREAD

**Issue by alepee** [neo4jrb/neo4j#1302]
Given a Node model

``` ruby
class User
  include Neo4j::ActiveNode
  before_update { self.newly_created = false }

  property :email
  property :newly_created, type: Boolean, default: true
end
```

``` ruby
u = User.create
u.update!(email: 'some@example.com')
```

Raises the following

```
Neo4j::ActiveNode::Persistence::RecordInvalidError:
    from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-7.0.9/lib/neo4j/active_node/persistence.rb:51:in `save!'
    from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-7.0.9/lib/neo4j/shared/persistence.rb:178:in `update!'
```

---

Neo4j database version:
`neo4j` gem version: 7.0.9
`neo4j-core` gem version: 6.1.4

**Comment by subvertallchris** [comment]
This is because your callback is returning `false`, telling the gem that the callback's action failed, which bails out of the update action entirely. Using `update!` tells it to raise `RecordInvalidError` but if you just do `update`, you'll see the `false` response that causes the problem.

You can work around this by changing your callback so it doesn't return `false`.

```
before_update { self.newly_created = false; nil }
```

Rails 5 changed this behavior, so we should probably update the gem to follow its lead. http://blog.bigbinary.com/2016/02/13/rails-5-does-not-halt-callback-chain-when-false-is-returned.html describes the old behavior (which you're seeing) and the new.

**Comment by alepee** [comment]
thanks @subvertallchris

**Comment by cheerfulstoic** [comment]
Re-opening as a reminder to follow ActiveRecord's lead
