### ISSUE TITLE
with_associations removes distinct

### ISSUE THREAD

**Issue by klobuczek** [neo4jrb/neo4j#1315]
When `with_associations` is appended to query chain a `distinct` is removed from the generated cypher. 

Additional information which could be helpful if relevent to your issue:
### Code example (inline, gist, or repo)

```
[55] pry(main)> >> AppRole.users.distinct
AppRole.users.distinct
 AppRole#users 
  MATCH (node2:`AppRole`)
  MATCH (node2)<-[rel1:`app_role`]-(result_users:`User`)
  RETURN DISTINCT(result_users) 

[56] pry(main)> >> AppRole.users.distinct.with_associations(:app_roles)
AppRole.users.distinct.with_associations(:app_roles)
 AppRole#users 
  MATCH (node2:`AppRole`)
  MATCH (node2)<-[rel1:`app_role`]-(result_users:`User`)
  WITH result_users
  OPTIONAL MATCH (result_users)-[:`app_role`]->(app_roles)
  WHERE (app_roles:`AppRole`)
  WITH 
    result_users, 
    collect(app_roles) AS app_roles_collection
  RETURN 
    result_users, 
    [app_roles_collection] 

```
### Runtime information:

Neo4j database version:
`neo4j` gem version: 8.0.0.rc.3
`neo4j-core` gem version: 7.0.0.rc.2

**Comment by cheerfulstoic** [comment]
Just trying this myself and it's actually returning distinct rows.  I'm pretty sure that this is because when you do an aggregation function (like `collect`/'sum'/'count'/etc...) it will return one aggregation value per distinct value that is being aggregated on.

Are you actually getting distinct user values or duplicates?

**Comment by klobuczek** [comment]
you are right, the aggregation implies distinct
