### ISSUE TITLE
ActiveRel doesn't have before/after_destroy callbacks

### ISSUE THREAD

**Issue by ramil8090** [neo4jrb/neo4j#1318]
Hello. I tried to use after_destroy method when delete relationship. But this method not fire. How i can use after_destroy callback on relationship. Thank you.

```
#ActiveRel model
class SomeRelation 
  include Neo4j::ActiveRel
  
  from_class :FromModel
  to_class :ToModel
  type 'some_relation'
  
  after_create ->(obj) { log }
  after_update ->(obj) { log }
  after_destroy ->(obj) { log }
end

#Using in controller
@fromModel.someRelation.delete(@toModel)
```

**Comment by cheerfulstoic** [comment]
Sorry for not responding sooner!

I'd suggest not using `delete` but rather `destroy` like `active_rel_object.destroy`.  If you call `delete` on an association you're basically creating a query which will execute a Cypher query with a `DELETE` clause which will bypass the models

Closing because I think everything is OK, but please let me know if there's still a problem
