### ISSUE TITLE
How to implement neo4j and microservices?

### ISSUE THREAD

**Issue by Vijeta141** [neo4jrb/neo4j#1326]
I am making an application based on microservices approach and want to use different instances of neo4j for different microservices. 
I have two independent services namely creative and project with their own neo4j instances. What would be the best way to create a relationship between a node of creative and a node of project ?

Additional information which could be helpful if relevent to your issue:

### Runtime information:

Neo4j database version:
`neo4j` gem version: 
`neo4j-core` gem version:

**Comment by cheerfulstoic** [comment]
Design questions don't really belong here so I'm going to close, but I'll give a quick shot at answering.  You might join the Neo4j public Slack group to ask there: https://neo4j.com/blog/public-neo4j-users-slack-group/

I don't think that the answer for Neo4j would be that different from SQL or any other database.  If you have two different database (one could be Neo4j and the other relational, even) you could store a reference to the object in the other DB (much like a foreign key).  In Neo4j foreign keys are discouraged because relationships do such things much better, but storing a unique identifier for an external resource is an entirely reasonable thing to do in any database.
