### ISSUE TITLE
Make it clear that RAILS_ENV=test is required for migrations

### ISSUE THREAD

**Issue by wjdhamilton** [neo4jrb/neo4j#1365]
This is a bit of silly thing, but there are several commands that are used to manipulate the database where the database can be specified by appending `[name]`.

e.g.`rake neo4j:start[test]`

However, this is not the case for migrations. 

For instance: `rake neo4j:migrate[test]` runs, but it does not migrate the test database. As you probably know, this is the correct command:

`rake neo4j:migrate RAILS_ENV=test`

It would be good if either the `[name]` element is respected, or if the command could print a warning to say that it isn't. 

Neo4j database version:
`neo4j` gem version: 8.0.10
`neo4j-core` gem version: 7.0.8

**Comment by cheerfulstoic** [comment]
It's a good point.  The difference comes in because using `RAILS_ENV=test` is from the Rails' convention.  `rake neo4j:start` (and the other `neo4j` commands) are intended to be independent of Rails or any other framework.  They are tasks from the `neo4j-rake_tasks` gem which can be included separately, if you like.  Thus you could do `rake neo4j:start[something_crazy]` and all it would do is just put the database into a `something_crazy` folder.  The only link between the two is the ports that you choose to configure the database with and specifying those same ports for your app.  Does that make sense?

**Comment by wjdhamilton** [comment]
It makes perfect sense! Thanks for taking the time to explain. I also see your conundrum: In order to print a warning, you would effectively have to respond to the idea that the gem is being run in a Rails project, which creates an explicit coupling to Rails. I suppose you could print such a warning whenever a command is forwarded to`neo4j-rake_tasks`, but I suppose the most reasonable way to deal with this would be to just put a line somewhere in the docs.

**Comment by cheerfulstoic** [comment]
Yeah, I think one way or another the docs need to be re-worked a bit to make it clear what's what.  I also just had a bit of a revelation that I shared [here](https://github.com/neo4jrb/neo4j/issues/1364#issuecomment-287880820)

Basically, the `neo4j-rake_tasks` gem is there to make it easier for beginners to manage a Neo4j server.  It's good because you can put some command lines in a tutorial and get people up and running ;) But there are other ways to use Neo4j (download the Mac/Win app, download the zip file and run the binary, or run a cloud service, for example) and not everybody uses the `neo4j-rake_tasks` gem.  So I'm thinking it makes sense to simply remove `neo4j-rake_tasks` as a dependency and have people require it only if they use it.  That way more of the details of it can go into the `README` for the repo and probably the readthedocs docs can link there, but tutorials can still do what they're doing with an extra addition of adding `neo4j-rake_tasks` to the `Gemfile`

Another thing that I think isn't widely known is that the `neo4j-rake_tasks` disable auth (again, to make things go more smoothly), and so it isn't normally recommended as a way of setting up Neo4j on production.
