### ISSUE TITLE
How do i backup my neo4j 2.2.2 to 3.1.2 and run it locally

### ISSUE THREAD

**Issue by ferryphang** [neo4jrb/neo4j#1367]
hello everyone, so i have a staging server that still use version 2.2.2 and i copy the graph.db/ to my local that run 3.1.2 and it wont start i already uncomment the 
#dbms.allow_format_migration=true
how do i solve this?

**Comment by cheerfulstoic** [comment]
Closing because this repo is for the Neo4j.rb Ruby gem.  You might ask on [StackOverflow](http://stackoverflow.com/questions/ask?tags=neo4j) or the [public Slack group](https://neo4j.com/blog/public-neo4j-users-slack-group/)

As far as I can tell, you're doing the right thing, but just make sure that both databases are shut down when you're doing the copy
