### ISSUE TITLE
[docs] Add database_cleaner example to testing section

### ISSUE THREAD

**Issue by jonblack** [neo4jrb/neo4j#1368]
The `database_cleaner` gem is a popular choice for cleaning a database during tests and has support for neo4j. Perhaps it's worth adding an example to the documentation?

E.g. with cucumber tests

```
// features/support/database_cleaner.rb
require 'database_cleaner'
require 'database_cleaner/cucumber'

DatabaseCleaner[:neo4j, connection: {
  type: :server_db,
  path: 'http://localhost:7475'
}].strategy = :truncation

Around do |_scenario, block|
  DatabaseCleaner.cleaning(&block)
end
```

I understand that this is more verbose than just using the code giving in the documentation:

```
// features/support/database_cleaner.rb
require 'database_cleaner'
require 'database_cleaner/cucumber'

Around do |_scenario, block|
  Neo4j::ActiveBase.current_session.query('MATCH (n) OPTIONAL MATCH (n)-[r]-() DELETE n,r')
  block.call
end
```

But it might be nice for people coming from `database_cleaner` to see this?

**Comment by cheerfulstoic** [comment]
:+1: thanks, this is on my list to do.  I was actually thinking of submitting a PR to the `database_cleaner` gem as well

**Comment by cheerfulstoic** [comment]
I added some documentation.  Thinking about it, I think it probably doesn't make sense for people to use the `database_cleaner` gem because the only thing you can really do in Neo4j is the "Deletion" strategy.  I'm thinking about making a PR to `database_cleaner` to make a link to the below documentation which explains things as well as taking away support for "truncation" and "transaction" in the Neo4j adaptor in `database_cleaner` because I think it just causes confusion since it's not really something that Neo4j does.

Here's the new section.  Curious for your thoughts:

http://neo4jrb.readthedocs.io/en/8.0.x/Miscellany.html#cleaning-your-database-for-testing

**Comment by RyanSnodgrass** [comment]
@cheerfulstoic I agree. `database_cleaner` gem adds a ton of features that I don't believe neo4j takes advantage of. We started using it then realized we were passing the delete cypher to the gem when we could have just written it by hand.

Our test deletion now looks like this
```ruby
# spec/rails_helper.rb
RSpec.configure do |config|
  # Clean Database
  config.before(:each) do
    delete_query = 'MATCH (n) OPTIONAL MATCH (n)-[r]-() DELETE n,r'
    Neo4j::ActiveBase.current_session.query(delete_query)
  end
end
```

The only thing I see `database_cleaner` gem being useful for is streamlining full database wipes including indexes and constraints

**Comment by cheerfulstoic** [comment]
:+1: Cool, I'll work on an appropriate change with the `database_cleaner` gem.  There are actually a few issues / PRs in progress ([here](https://github.com/DatabaseCleaner/database_cleaner/pull/481), [here](https://github.com/DatabaseCleaner/database_cleaner/pull/457), and [here](https://github.com/DatabaseCleaner/database_cleaner/pull/314)).

On a similar note to wiping the schema elements, I started working today on a `schema.yml` file which the gem would generate to generate a clean database (particularly for tests) so that you don't need to run through all of the migrations to setup a new database.  Still figuring out how to deal with `SchemaMigration` nodes, but hopefully it should make the testing experience more seamless.

**Comment by jonblack** [comment]
@cheerfulstoic Documentation looks great. Once minor issue: the comment above the Cypher queries relates to the same version:

    // For version of Neo4j before 2.3.0

**Comment by cheerfulstoic** [comment]
Fixed, thanks @jonblack !

Separately, I think I've got the schema functionality working if y'all would like to try it.  It's currently on the `8.1.x` branch, so you would need to do this in your `Gemfile`:

```ruby
gem 'neo4j', github: 'neo4jrb/neo4j', branch: '8.1.x'
```

This will give you two new rake tasks: `neo4j:schema:dump` and `neo4j:schema:load`.  The various migration tasks will automagically run `neo4j:schema:dump` which will generate a `db/neo4j/schema.yml` with all of the information about your constraints and indexes and it will automatically popular the `SchemaMigration` nodes.

`neo4j:schema:load` is for setting up a new database without needing to run all of your migrations.  If you run it in development everything should be smooth.  Everything should be smooth in test as well, but there's one thing that I should explain:

You should be able to do the plain old `MATCH (n) DETACH DELETE n` command to clear out the database.  The reason that you can't do that now is because acceptance tests (those that go through the web server) will complain that migrations haven't been run (because the records about them were removed).  In Rails, however, the [`skip_migration_check`](http://neo4jrb.readthedocs.io/en/8.1.x/Configuration.html#variables) configuration option is automatically set.  This turns off the check for migrations in web requests.

Does that all make sense?  Does it seem like a reasonable approach?
