### ISSUE TITLE
feature: case-insensitive enums

### ISSUE THREAD

**Issue by thefliik** [neo4jrb/neo4j#1418]
In my app, I'd like clients to provide enum params in all caps ([a convention](https://stackoverflow.com/a/3069863/5490505) I think is fairly common?). Currently, in order to accomplish this most easily, I'd need to have `enum property: [:VALUE_ONE, :VALUE_TWO]` which results in methods `Model.VALUE_ONE` or `Model.prefix_VALUE_ONE` which doesn't feel very Ruby esque. 

Would you accept a pull request to add a new option to `enum` of `_case_insensitive: true`? If enabled, this would downcase params before matching them against possible enum values. It would allow `enum property: [:value_one, :value_two], _case_insensitive: true` to match against `Model.create(property: 'VALUE_TWO')`.

Looks like this change would involve updates to [EnumConverter](https://github.com/neo4jrb/neo4j/blob/2b7caed832b0db7ff7b578fd48d5066d17350043/lib/neo4j/shared/type_converters.rb#L298) and ~[Neo4j::Shared::Enum::ClassMethods](https://github.com/neo4jrb/neo4j/blob/2b7caed832b0db7ff7b578fd48d5066d17350043/lib/neo4j/shared/enum.rb#L85)

**Comment by cheerfulstoic** [comment]
Yeah, I would definitely be fine with that change.  I almost wonder if it wouldn't make sense to just simply have it be case insensitive by default because if you have `enum property: [:value_one]` I can imagine that `VALUE_ONE` would be an entirely reasonable value for setting `value_one`.  But it would probably be good to have the option to opt-out of that (with `_case_sensitive: true`), still, to the current behavior.  What do you think?

**Comment by thefliik** [comment]
That makes sense to me. Case-insensitive enums definitely seem like a sensible default. Lets move the convo over to #1419.
