### ISSUE TITLE
bug: chained associations 

### ISSUE THREAD

**Issue by thefliik** [neo4jrb/neo4j#1421]
I appear to be on a bug finding tear. This was tested an a new, blank project with `community-3.1.5`. 

Given the following models:
```
class Person 
  include Neo4j::ActiveNode
end

class Signup 
  include Neo4j::ActiveNode

  has_many :out, :signup_shifts, type: :CONNECTOR, model_class: "ConnectorNode"

  def shifts
    signup_shifts.to_node.as(:n).where('n:`Shift`')
  end
end

class ConnectorNode 
  include Neo4j::ActiveNode

  has_one :in, :from_node, type: :CONNECTOR, model_class: "Signup"
  has_one :out, :to_node, type: :CONNECTOR, model_class: ["Shift", "Person"]
end

class Shift 
  include Neo4j::ActiveNode

  has_many :in, :signup_shifts, type: :CONNECTOR, model_class: "ConnectorNode"
end
```

# Expected Result

```
signup = Signup.create
#=> #<Signup uuid: "50a39cc7-4a01-4093-b71d-49502ba773bf">

signup.shifts
#=> #<QueryProxy Signup#signup_shifts#to_node []>
```

# Actual Result

```
signup = Signup.create
#=> #<Signup uuid: "50a39cc7-4a01-4093-b71d-49502ba773bf">

signup.shifts
#=> Neo4j::Core::CypherSession::CypherError:   Cypher error:
    Neo.ClientError.Statement.SyntaxError: Variable `result_to_node` not defined (line 1, column 157 (offset: 156))
    "MATCH (signup5) WHERE (ID(signup5) = {ID_signup5}) MATCH (signup5)-[rel1:`CONNECTOR`]->(node3:`ConnectorNode`) MATCH (node3)-[rel2:`CONNECTOR`]->(n) WHERE (`result_to_node`:`Shift` OR `result_to_node`:`Person`) AND (n:`Shift`) RETURN n"
```

# Additional Info

This bug can be worked around by using `result_to_node` as the `.as()` variable like so
```
def shifts
  signup_shifts.to_node.as(:result_to_node).where('result_to_node:`Shift`')
end
```
for that matter, you can just remove `.as()` entirely so long as you use `result_to_node` as the `where()` variable (though for anyone wanting to implement this workaround, you should include `.as()`)
```
def shifts
  signup_shifts.to_node.where('result_to_node:`Shift`')
end
```

Additionally, if `ConnectorNode` is changed to the following, then the query works normally:
```
class ConnectorNode 
  include Neo4j::ActiveNode

  has_one :in, :from_node, type: :CONNECTOR, model_class: false
  has_one :out, :to_node, type: :CONNECTOR, model_class: false
end
```

### Runtime information:

Neo4j database version: 3.1.5
`neo4j` gem version: 8.2.4
`neo4j-core` gem version: 7.2.3

**Comment by cheerfulstoic** [comment]
Yeah, variables in queries are a long standing problem.  There are a couple of ways that you can deal with this.  Perhaps the simplest way is to pass in the variable as an argument to the association

```ruby
  def shifts
    signup_shifts.to_node(:n).where('n:`Shift`')
  end
```

This sets the variable on the association so that it can be used later.  If you use `.as(:n)` then the gem can't reach back into the previous `QueryProxy` to set the right variable.  Actually, I think that `.as` was originally just intended to be used to start of a `QueryProxy` from a model like `Signup.as(:sign_up)`, so maybe it should be deprecated on `QueryProxy`

Another thing that you can do which is more verbose, but at least useful to know about:

```ruby
  def shifts
    to_nodes = signup_shifts.to_node
    to_nodes.where("#{to_nodes.identity}:`Shift`")
  end
```

The `identity` method is often really useful for getting the current variable for the `QueryProxy` in progress.  It's particularly useful if you're calling a method on a `QueryProxy` and that method had no control over the definition of the variable.

**Comment by thefliik** [comment]
Oh that is good to know about! Thanks 👍

**Comment by cheerfulstoic** [comment]
So do you think that this issue is closed or maybe we should leave it open to deprecate `as` on `QueryProxy` perhaps?

**Comment by thefliik** [comment]
Sounds like QueryProxy#as should be depreciated and the documentation on this issue should be clarified. I'll close this and open a new issue.

**Comment by thefliik** [comment]
Perhaps `query_as` should be depreciated / removed from `AssociationProxy` in favor of always specifying the query variable as an argument to the association method. Then, simply calling a query api method (like `.match()`) on an `AssociationProxy` would convert it to a query. i.e.

```
form.owner(:o, nil, chainable: true).match("")
```
