### ISSUE TITLE
question about bolt and faraday

### ISSUE THREAD

**Issue by ErikVanNorstrand** [neo4jrb/neo4j#1455]
Do I need to configure faraday in a specific way to work with the bolt api vs the http api.

http://neo4jrb.readthedocs.io/en/9.1.x/Setup.html#rails-configuration is not clear.

### Runtime information:

Neo4j database version: latest
`neo4j` gem version: latest
`neo4j-core` gem version: latest

**Comment by cheerfulstoic** [comment]
Hey @ErikVanNorstrand 

Faraday is used for the HTTP adapter.  The Bolt implementation doesn't use Faraday because it's not an HTTP standard.

We could easily clarify in this section that Faraday is just for HTTP:

http://neo4jrb.readthedocs.io/en/9.1.x/Setup.html#configuring-faraday

Would that make sense to you?

**Comment by ErikVanNorstrand** [comment]
Sorry for the delay in responding!

That would definitely help!

**Comment by cheerfulstoic** [comment]
Docs changed, thanks!
