### ISSUE TITLE
How I create undirectional relationships?

### ISSUE THREAD

**Issue by softwareeverything** [neo4jrb/neo4j#1473]
There are two User object on the neo4j. I want to create friendship between two user. How I can create this?

User1 -----friend----- User2

models/user.rb;

```
class User 
  include Neo4j::ActiveNode
  property :uid, type: Integer, constraint: :unique
  property :name, type: String
  property :created_at
  property :updated_at

  has_many :out, :ofriend, rel_class: :Friend,  model_class: :User
  has_many :in, :ifriend, rel_class: :Friend,  model_class: :User

  validates :uid, presence: true
  validates :name, presence: true
end
```

models/friend.rb;

```
class Friend

    include Neo4j::ActiveRel

    from_class :User
    to_class :User
    type :FRIEND
    creates_unique

end
```

### Runtime information:

`Neo4j database` version: neo4j 3.3.1
`neo4j gem` version: 9.0.7
`neo4j-core gem` version: 8.1.0

**Comment by cheerfulstoic** [comment]
You can do

```ruby
user1.ofriend << user2
```

or...

```ruby
user1.ofriend.create(user2)
```

Or, since you have an `ActiveRel` class:

```ruby
Friend.create(user1, user2)
```

Also, if you don't care about the direction of the relationship, you can use `:both` instead of `:in` or `:out` for the associations

Closing since this is a question (questions are better on Stack Overflow or Gitter), but feel free to comment further if something still isn't clear.
