### ISSUE TITLE
How to do cypher parameter?

### ISSUE THREAD

**Issue by softwareeverything** [neo4jrb/neo4j#1474]
For example, the sentence is `"I'm playing football"`
The parameter needs to be `"I\'m playing football"` to neo4j architecture...

I tried `variable.html_safe` but unfortunatelly, it doesn't work.

### Runtime information:

`Neo4j database` version: neo4j 3.3.1
`neo4j gem` version: 9.0.7
`neo4j-core gem` version: 8.1.0

**Comment by cheerfulstoic** [comment]
I'd need to see a bit more context.  In many cases, parameters are used automatically for you.  Like if you were to do `.where(text: "I'm playing football")`, it will build the `WHERE` clause using a parameter (you can see this by putting a `print_cypher` at the end of the chain)

If you are using `Query` objects the same is generally true.

If you are writing a raw Cypher query with a string, there are a couple of different places you can call a `query` method and provide a hash as the second argument.  This would look like `.query("MATCH (n:Something) WHERE n.text = {text}", text: "I'm playing football")`.

Closing because this is a question rather than a feature / bug request (feel free to ask questions on [Gitter](https://gitter.im/neo4jrb/neo4j) or [StackOverflow](https://stackoverflow.com/questions/ask?tags=neo4j.rb+neo4j+ruby)).  Happy to continue the discussion as needed here, though

**Comment by softwareeverything** [comment]
![image](https://user-images.githubusercontent.com/34370881/35348838-57b3b816-014a-11e8-850e-a414f0ffd553.png)

**Comment by cheerfulstoic** [comment]
There are a few things you could do.  The first thing that I would say is that you should never (or at least very rarely) inject data directly into a query string.  It can be:

 * Buggy if you have inappropriate escaping of strings
 * Slow because Neo4j can't optimize a query plan when the query string changes each time
 * Unsecure if this data is coming from a user because they could produce Cypher injection attacks

Ideally `sqlParametre` should be an array so that you can do this: 

```ruby
tablo = Word.query_as(:w).where('w.ad IN {ads}').params(ads: sqlParametre)
# or as a shortcut:
tablo = Word.query_as(:w).where('w.ad IN ?', sqlParametre)
```

But since you have an `ActiveNode` model you can also work at a higher level and replace lines 89 and 91 with this:

```ruby
kayitSayisi = Word.as(:w).where(ad: sqlParametre).pluck('SUM(w)').first
```

**Comment by cheerfulstoic** [comment]
Note for that last line that if `sqlParametre` is an array, the `neo4j` gem automatically detects that and creates the Cypher syntax `WHERE w.ad IN {param}` instead of `WHERE w.ad = {param}`

**Comment by softwareeverything** [comment]
It works fine now thank you @cheerfulstoic :)

**Comment by cheerfulstoic** [comment]
Great! :+1:
