### ISSUE TITLE
Export Neo4j data to svg file similar to Neo4j Browser graph

### ISSUE THREAD

**Issue by GaudamThiyagarajan** [neo4jrb/neo4j#1503]
Is there a way to export the neo4j data to svg output like the one that appears on the neo4j browser so we can use it inside our application.

**Comment by cheerfulstoic** [comment]
Hey @GaudamThiyagarajan 

You could probably write some code that would do that.  I believe that the Neo4j team was working on making parts of the Neo4j web interface open source so that people could use it to do other things, though I don't know the status of that.

It could make for a good gem, but it's not really in the scope of this one so I'm going to close this as an issue.

**Comment by GaudamThiyagarajan** [comment]
sure will try to make one. thanks
