### ISSUE TITLE
HA cluster configuration

### ISSUE THREAD

**Issue by andreasronge** [neo4jrb/neo4j#376]
How to configure Embedded and Server Neo4j in HA
Need documentation and maybe config.

**Comment by cheerfulstoic** [comment]
@subvertallchris What's the status of this?

**Comment by subvertallchris** [comment]
Out of the scope of this gem, IMO. If it belongs anywhere, it's in Core as
part of the code that starts an Embedded session.

**Comment by cheerfulstoic** [comment]
Good point.  It probably makes sense as another gem, even if that gem is very light.

I've actually been thinking about doing some work to vastly simplify the sessions and extract the Java API stuff to another part of `neo4j-core` or another gem.  Partly so that we have a nice way to integrate Bolt when that's more stable.  I need to understand it better first, though ;)  I'll ping you when I have a better idea

**Comment by cheerfulstoic** [comment]
Closing for now
