### ISSUE TITLE
Options for versioning of nodes

### ISSUE THREAD

**Issue by ghost** [neo4jrb/neo4j#617]
I'm using Papertrail in one of my mysql projects to track changes, what strategies are available for neo4j? I'm thinking of creating a neo4jrb fork of papertrail: https://github.com/airblade/paper_trail if there is not an existing solution. @subvertallchris @cheerfulstoic

**Comment by atbyrd** [comment]
@cheerfulstoic Has there been any more thought given to creating integration with papertrail. I wouldn't mind working on it but probably we need some guidance.

**Comment by cheerfulstoic** [comment]
There hasn't been any work, but I can certainly advise and I have various ideas.

Firstly, I usually look for support for MongoDB when adapting a gem for Neo4j.  Because of the schemaless nature and the need to define properties in the model it's a good starting point (but not perfect, of course)

Secondly, I could imagine multiple ways of storing history in Neo4j.  If you were going to store a basic log a relational (or even a document) DB might even be better than Neo4j for storing a long list of records without any relationships.  Of course that might not make a good general solution because probably not everybody would want to spin up another DB.

You could probably have a sort of linked-list trail of record history nodes leading off of the node in question.  This could solve potential problems with the node having lots and lots of relationships off of it (which can start to become a problem in Neo4j).  If you made the most recent record hang off and have another reference to the next-most-recent record then you could pretty easily get the most recent change events (I imagine that would be the most common query use case).  If not you could still have a relationship to the oldest node as well.  Either way, if you're breaking off and creating a new relationship each time to make this list, beware than Neo4j doesn't always recycle IDs well which means your database would continually grow (this was improved I think in 3.0 where they recycle after a restart and in 3.1 I think where they recycle continuously).

All that said... it might be best if this was something done as a Neo4j plugin which would automatically create the history as part of the running of the database.  This would be ideal because even with hooking into ActiveNode / ActiveRel models, there are still cases where you would miss changes if you are making mass-updates or just updates via Cypher you define yourself.  [This](https://github.com/graphaware/neo4j-changefeed) looks like it might do the job, though apparently that is sunsetted in favor of their [enterprise framework](http://graphaware.com/enterprise/).  If those don't work, you might be able to write your own plugin if you're reasonably handy with Java (and you might get some help on the [Neo4j public Slack group](https://neo4j.com/blog/public-neo4j-users-slack-group/))
