### ISSUE TITLE
RelCreateFailedError undefined method `r' for nil:NilClass

### ISSUE THREAD

**Issue by kohr** [neo4jrb/neo4j#679]
i'm stuck on this error. trying to create the relationship below. it have the same for any relationship creation. i'm lost ....
i use     gem "neo4j", "~> 4.1.0"
do you see where it can come from ?

     Class Resume 
       include Neo4j::ActiveRel 
       property :order

        from_class User
        to_class :any
        type 'RESUME'
        set_classname
      end

Neo4j::ActiveRel::Persistence::RelCreateFailedError: Unable to create relationship. from_node: #<User:0x007fa22d9f2460>, to_node: #<Job:0x007fa22e371608>, error: undefined method 'r' for nil:NilClass
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/active_rel/persistence.rb:97:in 'rescue in _rel_creation_query'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/active_rel/persistence.rb:89:in '_rel_creation_query'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/active_rel/persistence.rb:65:in '_create_rel'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/active_rel/persistence.rb:26:in 'create_model'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/shared/callbacks.rb:40:in 'block (2 levels) in create_model'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in 'call'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in '_run_callbacks'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in '_run_create_callbacks'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in 'run_callbacks'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/shared/callbacks.rb:40:in 'block in create_model'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-core-4.0.1/lib/neo4j/transaction.rb:84:in 'run'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/shared/callbacks.rb:39:in 'create_model'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/shared/persistence.rb:36:in 'create_or_update'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/shared/callbacks.rb:35:in 'block in create_or_update'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in 'call'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in '_run_callbacks'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in '_run_save_callbacks'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in 'run_callbacks'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/shared/callbacks.rb:35:in 'create_or_update'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/active_rel/persistence.rb:14:in 'save'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/shared/validations.rb:18:in 'save'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/active_rel/callbacks.rb:11:in 'save'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/active_rel/persistence.rb:41:in 'block in create'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/active_rel/persistence.rb:37:in 'tap'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/active_rel/persistence.rb:37:in 'create'
/Users/xxx/Sites/hroads/rails/hroads/lib/parsers/cv/Base.rb:29:in 'block in addJob'
/Users/xxx/Sites/hroads/rails/hroads/lib/parsers/cv/Base.rb:23:in 'each'
/Users/xxx/Sites/hroads/rails/hroads/lib/parsers/cv/Base.rb:23:in 'addJob'
/Users/xxx/Sites/hroads/rails/hroads/lib/parsers/cv/Hireability.rb:26:in 'block in parse'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:237:in 'block in each'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:236:in 'upto'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:236:in 'each'
/Users/xxx/Sites/hroads/rails/hroads/lib/parsers/cv/Hireability.rb:26:in 'map'
/Users/xxx/Sites/hroads/rails/hroads/lib/parsers/cv/Hireability.rb:26:in 'parse'
/Users/xxx/Sites/hroads/rails/hroads/lib/tasks/hroads.rake:12:in 'block (3 levels) in <top (required)>'
/Users/xxx/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in 'eval'
/Users/xxx/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in '<main>'
NoMethodError: undefined method 'r' for nil:NilClass
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/active_rel/persistence.rb:95:in '_rel_creation_query'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/active_rel/persistence.rb:65:in '_create_rel'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/active_rel/persistence.rb:26:in 'create_model'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/shared/callbacks.rb:40:in 'block (2 levels) in create_model'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in 'call'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in '_run_callbacks'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in '_run_create_callbacks'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in 'run_callbacks'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/shared/callbacks.rb:40:in 'block in create_model'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-core-4.0.1/lib/neo4j/transaction.rb:84:in 'run'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/shared/callbacks.rb:39:in 'create_model'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/shared/persistence.rb:36:in 'create_or_update'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/shared/callbacks.rb:35:in 'block in create_or_update'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in 'call'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in '_run_callbacks'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in '_run_save_callbacks'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in 'run_callbacks'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/shared/callbacks.rb:35:in 'create_or_update'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/active_rel/persistence.rb:14:in 'save'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/shared/validations.rb:18:in 'save'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/active_rel/callbacks.rb:11:in 'save'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/active_rel/persistence.rb:41:in 'block in create'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/active_rel/persistence.rb:37:in 'tap'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/neo4j-4.1.1/lib/neo4j/active_rel/persistence.rb:37:in 'create'
/Users/xxx/Sites/hroads/rails/hroads/lib/parsers/cv/Base.rb:29:in 'block in addJob'
/Users/xxx/Sites/hroads/rails/hroads/lib/parsers/cv/Base.rb:23:in 'each'
/Users/xxx/Sites/hroads/rails/hroads/lib/parsers/cv/Base.rb:23:in 'addJob'
/Users/xxx/Sites/hroads/rails/hroads/lib/parsers/cv/Hireability.rb:26:in 'block in parse'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:237:in 'block in each'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:236:in 'upto'
/Users/xxx/.rvm/gems/ruby-2.1.5/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:236:in 'each'
/Users/xxx/Sites/hroads/rails/hroads/lib/parsers/cv/Hireability.rb:26:in 'map'
/Users/xxx/Sites/hroads/rails/hroads/lib/parsers/cv/Hireability.rb:26:in 'parse'
/Users/xxx/Sites/hroads/rails/hroads/lib/tasks/hroads.rake:12:in 'block (3 levels) in <top (required)>'
/Users/xxx/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in 'eval'
/Users/xxx/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in '<main>'

**Comment by subvertallchris** [comment]
What's the command you're using to create the rel?

**Comment by kohr** [comment]
Resume.create(from_node: User, to_node: Job)

**Comment by cheerfulstoic** [comment]
Ooo oooh!  I know this one!

The value need to be actual node objects.  So lik:

    Resume.create(from_node: user, to_node: job)

Of course you need to define those variables first

**Comment by kohr** [comment]
sorry, it is actual node objects ;)
i thought it was in the trace, it's a user and a job that are created before :
         #User:0x007fa22d9f2460, to_node: #Job:0x007fa22e371608, error: undefined method 'r' for nil:NilClass

if i simplify the code is :

          user = Neo4j::Session.query.merge(q: {User: {email: data['email']}}).pluck(:q).first
          job = Neo4j::Session.query.merge(q: {Job: {name: data['name']}}).pluck(:q).first
          Resume.create(from_node: user, to_node: job)

**Comment by subvertallchris** [comment]
If you do "Resume.new" and then call "valid?", does it say all is good? I'm
guessing yes, but let's start there.

**Comment by subvertallchris** [comment]
With the same from_node and to_node arts, of course. It should give a
different error if there's a validation issue.

Also, any reason you're using the `type` and `set_classname` class methods
in your model? You shouldn't need to with 4.1.0. This def shouldn't have an
impact on this error, just pointing it out before I forget.

**Comment by kohr** [comment]
thanks for your answer. i've hard time finding the up to date doc ;) i removed both lines from Resume

       r = Resume.new
       puts r.valid?

this says "true"

**Comment by cheerfulstoic** [comment]
Not sure if Chris has left yet, but I think he was suggesting doing this:

    Resume.new(from_node: user, to_node: job)

**Comment by kohr** [comment]
sorry...
same result with that too

**Comment by subvertallchris** [comment]
Still here, though I just got off a plane and will be running around in a
moment.

Pretty sure I can explain why it's complaining about an "r" method but I
want to look at code to double check. That's supposed to get called, but
it's calling on a nil object because the rel either isn't being created or
returned for some reason. If you can, go into the neo4j web console and see
if it's actually creating rels and just not returning them or if it's
failing to create completely.

Try setting the to_class in your model to Job... I don't think that'd do it
but give it a shot. Also remove the "type" and "set_classname" methods, I
wonder if using both of them could be messing something up, though I doubt
it. Also, if you do this in the rails console, does it output to the
terminal? Seeing the cypher it's generating would tell us everything.

**Comment by kohr** [comment]
no, it's not creating the rels (but the nodes yes of course)
i removed type and set_classname and set the to_class to Job, 
same result

i'm not sure i understand your last question, this error outputs in the terminal : 
Neo4j::ActiveRel::Persistence::RelCreateFailedError: Unable to create relationship. from_node: #<User:0x007f86fb82d898>, to_node: #<Job:0x007f87010bad80>, error: undefined method `r' for nil:NilClass

and what can i do to see the generated cypher ?

**Comment by subvertallchris** [comment]
If Cypher isn't popping up, it means this is one of the queries that doesn't log or you're not using rails console. Either way, no big deal, we can work around it.

Ahh I know exactly what's causing it! It's happening because you're creating nodes without UUIDs. The rel creation query looks like this:

```
Neo4j::Session.query.match(n1: from_class.mapped_label_name, n2: to_class.mapped_label_name)
          .where("n1.#{from_class.primary_key} = {from_node_id}")
          .where("n2.#{to_class.primary_key} = {to_node_id}")
          .params(from_node_id: from_node.id, to_node_id: to_node.id)
          .send(create_method, ("(n1)-[r:`#{type}`]->(n2)"))
          .with('r').set(r: props).return(:r).first.r
```
It calls `id` on each node, which expects to return their primary key values. Since you're using `merge` to create nodes, these values are nil. You can get around this by modifying your initial queries that create the nodes:

```
user = Neo4j::Session.query.merge(q: {User: {uuid: SecureRandom.uuid, email: data['email']}}).pluck(:q).first
job = Neo4j::Session.query.merge(q: {Job: {uuid: SecureRandom.uuid, name: data['name']}}).pluck(:q).first
Resume.create(from_node: user, to_node: job)
```

@cheerfulstoic, will core convert those to params automatically? I don't think it will. If I'm right, you should do it like this:

```
user = Neo4j::Session.query.merge('(q:User { uuid: {uuid}, email: {email}) ON CREATE SET q.uuid = {uuid}`).params(uuid: SecureRandom.uuid, email: data['email']).pluck(:q).first
```
Follow the same basic template for `job`. You'll get much better performance and you won't be susceptible to Cypher injection attacks. If possible, you should do all of these together in one query.

**Comment by kohr** [comment]
great, thank you !!!
this works (i use concerns)

              obj = Neo4j::Session.query.merge(q: {self.name.to_sym => params})
                   .on_create_set(q: {uuid: SecureRandom.uuid})
                   .pluck(:q).first

is it possible that it was working with 4.0 and not 4.1 ? because it was working at some point before it broke, i'm not sure if i updated the gem in between...

What's the best practice to handle relations creation ? since now the merge is working for the nodes, if i leave 

         Resume.create(from_node: user, to_node: job)

i'm having a relation duplicated each time i run the command

**Comment by subvertallchris** [comment]
It is very possible. I'm not sure if it happened between 4.0 and 4.1 but at some point, I changed that query to use UUIDs instead of database-provided IDs (`neo_id`) because those weren't working with params. I could change it back now and we'd see a slight performance boost, plus ActiveRel would become somewhat more compatible with Neo4j::Core, so... this is something I'll think about.

I wouldn't use the `on_create_set` method right now, it doesn't use params. Same goes for that `merge` method. You're susceptible to Cypher injection and you take a performance hit. We need to go through Neo4j::Core and fix all of those queries. You can use strings with both of those methods and call `params` to set it explicitly for now.

Add `creates_unique_rel` to your model and it'll use `CREATE UNIQUE` instead of `CREATE` to stop those duplicate relationships. If you prefer `merge`, you can write a query manually that does the same thing.

**Comment by kohr** [comment]
thank you. you're doing such a great job, those toys are impressive ;)
i'm still a beginner (both in ruby and neo4j), could you give me an overview of what the query string would look like ?

**Comment by subvertallchris** [comment]
Thanks! We do our best. :-)

Which query string are you looking for? Pretty much every Neo4j::Core::Query method will accept a string instead of a hash. At the most basic, you just want to write a piece of Cypher as an argument, add the param to it, and then call `params` to set the value later. If you want to create the rel, it could be as simple as this:

```
Neo4j::Session.query.match(u: :User, j: :Job).where("u.uuid = {user_id}, j.uuid = {job_id}").merge("(u)-[r1:RESUME]->(j)").params(user_id: user.id, job_id: job.id).pluck(:r1) 
```

Rule of thumb in Neo is that any time you are feeding property values into a query, you should make sure you're using params. Neo4j::ActiveNode and ActiveRel will do this for you: if you do `Job.where(name: params[:name])`, it creates the params automatically. Many methods in Core::Query will do it, too, but we still have to go through all of them and fix some that don't.

Check Neo's manual for more info about parameterized queries.

Not to nitpick, but you might want think use a different rel type instead of `RESUME`. Neo4j data modeling puts a lot of emphasis on readability, just like Ruby, and rel types usually suggest an action to help keep things logical. "User applied to job," would turn into `(:User)-[:APPLIED_TO]->(:Job)`.

**Comment by subvertallchris** [comment]
Gonna close this one, let us know if you need a hand with anything.
