### ISSUE TITLE
create_unique class method

### ISSUE THREAD

**Issue by subvertallchris** [neo4jrb/neo4j#688]
We should have a `create_unique` class method that uses this Cypher function to create or match nodes. It'd be similar to `find_or_create_by` except it wouldn't be an n+1 query.

**Comment by cheerfulstoic** [comment]
What about `merge`?

**Comment by cheerfulstoic** [comment]
I just added `.merge` and `.find_or_create` methods (see https://github.com/neo4jrb/neo4j/commit/ae9204d87ec6ce253376aa21cfe59e5e162225ae).  It seems like `CREATE UNIQUE` requires a relationship to be part of the pattern.  What sort of use case were you thinking about?

Also, I think it makes sense to support `CREATE UNIQUE`, though I believe it's deprecated  (probably because `MERGE` doesn't do everything `CREATE UNIQUE` can yet).  See here: http://graphaware.com/neo4j/2014/07/31/cypher-merge-explained.html
