### ISSUE TITLE
Node validation with bool property

### ISSUE THREAD

**Issue by AfonsoTsukamoto** [neo4jrb/neo4j#706]
Hi!

I have a node with a boolean attribute with presence validation:

```
class UserNode
  include Neo4j::ActiveNode

  property :email, index: :exact, constraint: :unique
  property :registered, type: Boolean, default: false,
   index: :exact

  validates_presence_of :email
  validates_presence_of :registered
end
```
But it fails the validation every time the  boolean property is set to false.

```
u = UserNode.new
=> #<UserNode email: nil, formatted_name: nil, linkedin_id: nil, pg_id: nil, registered: false>
u.update_attributes(email: 'example@neo.com', registered: false)
=> false
u.save
=> false
u.save!
=> Neo4j::ActiveNode::Persistence::RecordInvalidError: Registered can't be blank
u.update_attributes(registered: true)
=> true
u.save
=> true
```
Am I doing something wrong or is it a bug?

Thank you.

**Comment by cheerfulstoic** [comment]
I think that this is expected behavior.  In ActiveSupport, `present?` means not `blank?`, and `blank?` is: "false, empty, or a whitespace string. For example, ”, ‘ ’, nil, [], and {} are all blank."

http://apidock.com/rails/Object/blank%3F

It seems like you probably want `validates_inclusion_of`:

http://stackoverflow.com/questions/4402693/how-to-validate-a-field-value-at-activerecord-model-in-ruby-on-rails

Feel free to reopen

**Comment by AfonsoTsukamoto** [comment]
Ok, it actually makes sense. Did a test using ActiveRecord and it has the same behaviour. 

That naming convention is a bit tricky, though. But I can live with that :)

Thanks!
