### ISSUE TITLE
How let a search engine to access the DB

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#707]
I need to make searchable a well defined subset of the data maintained in my DB.
In other words, I need google, bing or yahoo to be able to indicize part of the contents and to hide other parts.

I'm not sure how to approach this, because I shouldn't like to open the DB, but, if I make some public copies, I cannot imagine a way to let the user know the logical address to reach the data found in the original DB after having logged in.

Any idea or any experiences in this direction?

**Comment by subvertallchris** [comment]
I'd post this one on SO, you'll get better answers there because it's not a Neo4j question. I think there is a way to let the googlebot know where it can find indexable content but I don't know what it is offhand. It definitely will not come directly from your database, it'll need to be a page of some sort.
