### ISSUE TITLE
ids of relations

### ISSUE THREAD

**Issue by garmoshka-mo** [neo4jrb/neo4j#709]
https://github.com/neo4jrb/neo4j/wiki/Neo4j-v3-Unique-IDs#id_property-primary-key

> Unique IDs are not generated for relationships or ActiveRel models because their IDs should not be used. 

Why? Why "their IDs should not be used. "?

> If you find yourself in situations where you need relationship IDs, you probably need to define a new ActiveNode class!

Why new **ActiveNode**?

Identification of relationships - is common situation.
Let's take as example code from project introduction:

    class Student
      include Neo4j::ActiveNode
      property :name
      property :age
      has_many :out, :lessons, type: 'enrolled_in'
    end

Let's say we want to count visits of student.
We add new relation type "visited" with property "date"
Now teacher added two visits of him for one day and wants to fix this:
1. Teacher opens list of relations with type 'visits'
2. Chosen one of them - form displaying single relationship properties
4. Now he wants delete exactly this relation record, not others.

How to do this?

**Comment by subvertallchris** [comment]
You'd do that by matching from the teacher to the student.

```
MATCH (s:Student)-[r1:VISITED { date: {visit_date} }]->(t:Teacher) WHERE ID(s) = {student_id} AND ID(t) = {teacher_id} DELETE r1
```

In Neo4j.rb, you'd do:
```
# Assuming both student and teacher have been returned to nodes...
rel = teacher.visited_students(:s, :r).match_to(student).rel_where(date: some_date).pluck(:r)
rel.destroy
```

If we provided UUIDs for relationships, it would encourage users to do `MATCH (t:Teacher)-[r:VISITED_BY { uuid: {rel_uuid} }]->(s:Student)`, which is a terrible idea if there are better options because it would touch every relationship between nodes of those labels. Relationship properties cannot be indexed so filtering a match using them should always be done relative to nodes, if possible.

**Comment by cheerfulstoic** [comment]
How is querying on the `date` property of the relationship better than querying on the `uuid` property of the relationship?

**Comment by subvertallchris** [comment]
It's finding two nodes and filtering the relationships between them instead
of seeking one property on all relationships between all nodes with those
labels.

**Comment by cheerfulstoic** [comment]
Oh, right, good point ;)

**Comment by garmoshka-mo** [comment]
> You'd do that by matching from the teacher to the student.

In my case, i have several relations between same object with same properties.

>  teacher added two visits for one day and wants to fix this:

E.g. two records for '4 Sep'
(Student1)-[visited {date: '1 Sep'}]->(Math)
(Student1)-[visited {date: '2 Sep'}]->(Math)
(Student1)-[visited {date: '4 Sep'}]->(Math)
(Student1)-[visited {date: '4 Sep'}]->(Math)

Need to remove 1 specific record.

Okay, now developer can add unique index to date, though it is sort of headache.
And what if business logic actually allows to visit lesson two times a day (morning/evening)

This is **not mandatory** to work with relations in each app architecture,
but it often happens. Another example is some roles like this:
(John)-[repairer]->(Bike's garage)
(John)-[senior repairer]->(Car's garage)
(John)-[manager]->(Car's garage)

Yes, on web-form of relationship management we can add logic, which will filter by
1. person.id
2. place.id
3. role.name
This is instead of simple search by role.id.
This adds certain headache to developer (how should i filter? if +filter by role.name will be enough?
or need to see if there is another properties? customer told, that there might appear
role ranks - 1..5 - how it will reflect on business logic later? gosh!)
Instead of simple search by role.id...
And ruby by itself is designed to save developer from headaches.


> `MATCH (t:Teacher)-[r:VISITED_BY { uuid: {rel_uuid} }]->(s:Student)` , which is a terrible idea if there are better options because it would touch every relationship between nodes of those labels.

What is required in described examples, is:
     MATCH ()-[r { uuid: {rel_uuid} }]->() RETURN r

And if relationships will be indexed - nothing scary in such request, it will be probably even more efficient,
than 1. lookup through nodes A, 2. then through nodes B, 3. and then find relations between them

> Relationship properties cannot be indexed 

Yes, they cannot be indexed by schema index (strange why, though maybe it will be implemented in future in neo4j?)
Though legacy indexes and auto indexes allow to index relationships:
http://neo4j.com/docs/stable/auto-indexing.html
http://neo4j.com/docs/stable/indexing-relationships.html
Maybe it is not easy to implement in neo4jrb now and schema indexes preferable,
but except technical issues i don't see for now why relationship ids aren't desirable,
why neo4jrb should prevent usage of intuitive convenient logic

**Comment by subvertallchris** [comment]
We don't support legacy indexing because of the hurdles associated with maintaining it. I don't use it in my own projects for the same reason. Neo4j.rb doesn't prevent you from creating IDs on relationships using callbacks or by modifying the source, but we can't encourage people to do what you're describing. Without relationship indexes, `MATCH ()-[r { uuid: {rel_uuid} }]->() RETURN r` is a scary query and providing relationship IDs would encourage people to do it, then they'd be mad at us or Neo4j when it performs poorly.

**Comment by cheerfulstoic** [comment]
Can't you just do `.where("ID(rel) = {rel_neo_id}").params(rel_neo_id: rel.neo_id)`?  You should still querying between the two nodes, but there is a unique relationship ID.

Note: Neo4j doesn't recommend using their internal IDs as permanent identifiers because they are pointers to an offset in a file on disk and they reserve the right to shuffle the file around for efficient management of the DB

**Comment by garmoshka-mo** [comment]
Yes, on deletion of nodes/rels ids are shifted, so this can lead to wrong data update, 
when i have web-forms opened for some time.

Ok, clear, so due to absence of schema tools this can't be easily implemented here
Yes, like you suggested, i did some changes in source codes for my project to have rel.IDs

Thanks for explanations
