### ISSUE TITLE
Neo4j._query do not work

### ISSUE THREAD

**Issue by garmoshka-mo** [neo4jrb/neo4j#710]
https://github.com/neo4jrb/neo4j/wiki/Neo4j%3A%3ACore-Cypher#neo4jquery-and-neo4j_query

     q = Neo4j._query("START n=node(42) RETURN n")
gives:

     Minitest::UnexpectedError: NoMethodError: undefined method `_query' for Neo4j:Module

This, though works (found in sources)

     Neo4j::Session.query.match('()-[r]-()').pluck('DISTINCT r')

**Comment by subvertallchris** [comment]
That documentation is under the "Legacy" heading in the column on the right and refers to the 2.x version of the gem. It hasn't been updated since 2012. You should `Neo4j::Session.current.query` if you want to write Cypher directly. The Neo4j-core gem provides this functionality, see https://github.com/neo4jrb/neo4j-core/wiki.
