### ISSUE TITLE
Get raw response object from ActiveNode

### ISSUE THREAD

**Issue by ariieh** [neo4jrb/neo4j#742]
I'd love a method on ActiveNode objects that gets me the raw response node the Neo4j db gives you when you post to create a node -- something like [this](http://neo4j.com/docs/stable/rest-api-nodes.html#rest-api-create-node):
````
{
  "extensions" : { },
  "outgoing_relationships" : "http://localhost:7474/db/data/node/8/relationships/out",
  "labels" : "http://localhost:7474/db/data/node/8/labels",
  "traverse" : "http://localhost:7474/db/data/node/8/traverse/{returnType}",
  "all_typed_relationships" : "http://localhost:7474/db/data/node/8/relationships/all/{-list|&|types}",
  "self" : "http://localhost:7474/db/data/node/8",
  "property" : "http://localhost:7474/db/data/node/8/properties/{key}",
  "properties" : "http://localhost:7474/db/data/node/8/properties",
  "outgoing_typed_relationships" : "http://localhost:7474/db/data/node/8/relationships/out/{-list|&|types}",
  "incoming_relationships" : "http://localhost:7474/db/data/node/8/relationships/in",
  "create_relationship" : "http://localhost:7474/db/data/node/8/relationships",
  "paged_traverse" : "http://localhost:7474/db/data/node/8/paged/traverse/{returnType}{?pageSize,leaseTime}",
  "all_relationships" : "http://localhost:7474/db/data/node/8/relationships/all",
  "incoming_typed_relationships" : "http://localhost:7474/db/data/node/8/relationships/in/{-list|&|types}",
  "metadata" : {
    "id" : 8,
    "labels" : [ ]
  },
  "data" : { }
}
````

I'm dealing with spatial indexes, which this gem doesn't appear to support out of the box, so I need to post and get on my own -- but I would still like to ``create`` with the ORM, hence my desire for a method like this. ``serializable_hash`` doesn't cut it, unfortunately.

**Comment by subvertallchris** [comment]
That's an interesting request. It's actually a bit more of a Neo4j-core issue, since that's where the response is processed. What'll make it difficult is that all of that data is discarded after the response is wrapped. The flow is essentially:

* Cypher response is received
* "Columns" (objects requested for return) are inspected for keys identifying them as complete node or relationship objects
* `Neo4j::Server::CypherNode` and/or `Neo4j::Server::CypherRelationship` objects are created using keys you listed from the data above
* The `wrapper` instance method is called which begins the ActiveNode/ActiveRel object instantiation. The underlying CypherX object is available in the `_persisted_obj` instance method.

So the trick will be figuring out the keys that Neo4j Spatial adds to the response, making them available to the `_persisted_obj`, then creating instance methods that let you get to them from the ActiveNode object. I'd love to get support in for the Neo4j Spatial plugin, so I'm happy to help if I can.

I'm signing off for now but if you're around during the day, pop into our [Gitter chat](https://gitter.im/neo4jrb/neo4j) tomorrow and we can brainstorm on it.

**Comment by cheerfulstoic** [comment]
I also think that it makes sense to have the method that returns this data on the CypherNode so that all accesses are through the `_persisted_obj`

**Comment by ariieh** [comment]
Thanks for the replies guys -- I have some thoughts, will try to be on chat today.

**Comment by subvertallchris** [comment]
Going to close this, please reopen and let us know if you think there's anything to be done here.
