### ISSUE TITLE
Serializing data

### ISSUE THREAD

**Issue by brancusi** [neo4jrb/neo4j#744]
Hi,

Is there a new solution for using the active_model_serializer gem? The current one listed in the wiki no longer seems to apply.

Also, in general, is there a better approach to putting out json? How would you guess most people are rendering api endpoints?

Thank you

**Comment by subvertallchris** [comment]
I'm not aware of issues with it, though I honestly have never used it myself. What are you running into when you try using it?

I use jbuilder for JSON. As long as I use the oj gem and avoid partials, performance is very good.

**Comment by brancusi** [comment]
Thanks so much for the quick response.

So in the [wiki](https://github.com/neo4jrb/neo4j/wiki/Neo4j::Rails-Third-Party) there is a guide for getting AMS to work. It states adding this in an initializer:

```ruby
Neo4j::Rails::Model.send(:include, ActiveModel::SerializerSupport)
Neo4j::Rails::Relationships::NodesDSL.delegate(:active_model_serializer, to: :to_a)
```
When I try this I get:

```bash
uninitialized constant Neo4j::Rails (NameError)
```

If I just install AMS as I would normally without the initializer, the serializers are not invoked when rendering json.

I mainly like AMS because it gives puts out the JSON exactly as needed by ember-data. Sideloaded, proper ids, removes duplicate result when including relationships.

I realize this may all be very different in Neo4j, but I would like to give it a shot and see how it goes.

When using jbuilder, how would you go about putting out json that looks like this:

```json
{
    "posts": [
        {
            "id": "p001",
            "title": "Title",
            "user": "u001",
            "comments": [
                "c001",
                "c002"
            ]
        },
        {
            "id": "p002",
            "title": "Title",
            "user": "u002",
            "comments": [
                "c003",
                "c004"
            ]
        }
    ],
    "comments": [
        {
            "id": "c001",
            "body": "Body1"
        },
        {
            "id": "c002",
            "body": "Body2"
        },
        {
            "id": "c003",
            "body": "Body3"
        },
        {
            "id": "c004",
            "body": "Body4"
        }
    ],
    "users": [
        {
            "id": "u001",
            "name": "Howard"
        },
        {
            "id": "u002",
            "name": "Howard"
        }
    ]
}
```

The main thing I struggle with is removing the duplicate sideloaded data.

With AMS, we can just do:

```ruby
render json: posts
```

and using a serializer that looks like:

```ruby
class PostSerializer < ActiveModel::Serializer
  attributes :id, :title

  has_many :comments
  has_one :user
end
```

We would get the sample json above. Duplicates would be removed. All comments and users would be sideloaded.

Thank you

**Comment by subvertallchris** [comment]
That links to the legacy documentation and applies to the 2.x version of
the gem. We're at 4.something now and preparing for 5.0, so none of that
has any value here.

I seem to remember an issue or two in the past where someone mentioned they
were using AMS for something but I can't remember what. I'll see if I can
try it out myself tomorrow. In the meantime, I can't really give good
advice on writing your example from jbuilder cause I'm on my phone. Its API
is very simple, IMO. It's essentially a template system for JSON, so it
makes manipulating data easy.

**Comment by brancusi** [comment]
Thanks Chris, that would be a huge help!

**Comment by cheerfulstoic** [comment]
Also, I've successfully used `active_model_serializer` in the [neo4j-meta_model](https://github.com/neo4jrb/neo4j-meta_model) project, so you might want to check that out.  You could either look at the code, or alternatively you could include neo4j-meta_model in your project if you're looking for API endpoints.

**Comment by cheerfulstoic** [comment]
Some files / directories of interest:

https://github.com/neo4jrb/neo4j-meta_model/blob/master/config/initializers/active_model_serializer.rb

https://github.com/neo4jrb/neo4j-meta_model/tree/master/app/serializers/neo4j/meta_model

https://github.com/neo4jrb/neo4j-meta_model/tree/master/app/models

The code is a bit meta (obviously ;).  Let me know if you have any questions

**Comment by brancusi** [comment]
Thank you for the links. I have been trying to get this to work. I've tried in several projects and eventually cloned the sample app project and tried there. I keep getting this when I actually try to visit the mounted url:

```
Completed 500 Internal Server Error in 2563ms

ActionView::Template::Error (Pre compilation failed for: div.list-group
  each child in node
    model-list-item model=child.[0] sub_hierarchy=child.[1]


. Compiler said: TypeError: undefined is not an object (evaluating 'close.path.original')
  (in /Users/Limix/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/neo4j-meta_model-0.3.5/app/assets/javascripts/templates/components/model-list.emblem)):
     7:     var meta_model_root_path = '#{root_path}';
     8:
     9:   = stylesheet_link_tag    'meta_model', media: 'all'
    10:   = javascript_include_tag 'meta_model'
    11:
    12:   = csrf_meta_tags
    13:
  barber (0.9.0) lib/barber/precompiler.rb:25:in `rescue in compile'
  barber (0.9.0) lib/barber/precompiler.rb:23:in `compile'
  barber (0.9.0) lib/barber/precompiler.rb:8:in `compile'
  barber-emblem (0.1.2) lib/barber/emblem/ember_precompilers.rb:10:in `compile'
  barber-emblem (0.1.2) lib/barber/emblem/ember_precompilers.rb:6:in `call'
  emblem-rails (0.2.2) lib/emblem/rails/template.rb:52:in `precompile_ember_emblem'
  emblem-rails (0.2.2) lib/emblem/rails/template.rb:20:in `evaluate'
  tilt (1.4.1) lib/tilt/template.rb:103:in `render'
```

Steps I took.

1. Bundle installed
1. added to routes.rb: ```mount Neo4j::MetaModel::Engine => "/"```
1. rake neo4j:install[community-2.2.0]
1. rake neo4j:start
1. visited localhost:7474 and updated credentials to neo4j, bar
1. added credentials to application.rb: ```config.neo4j.session_options = { basic_auth: { username: 'neo4j', password: 'bar'} } ```
1. rails s
1. visit: localhost:3000/

Thank you

**Comment by cheerfulstoic** [comment]
Ah, right, shoot.  Sorry, there's an issue with the emblem gem (templating library for Ember) which is causing this problem.  I need to revisit it and maybe use a different library.  You can see a discussion about the issue here:

https://github.com/alexspeller/emblem-rails/issues/36

In the meantime, you might just try copying some code for the serializers from the project

**Comment by brancusi** [comment]
Thanks Brian, will do.

**Comment by cheerfulstoic** [comment]
@brancusi Hello!  I've fixed `neo4j-meta_model` since this discussion stopped, but I'm curious if you've found a solution.  I've got somebody else (pinging @jamilabreu) who's having similar issues

**Comment by feedthebayer** [comment]
Hey guys, I am using active_model_serializers in my Rails API 4.2.3 project. It worked great for me out of the box by just following the standard AMS install instructions.

The only hiccup I ran into is, on the index route, needing to `render json: Model.all.to_a` instead of just `render json: Model.all`. Is that a bug?

By the way, you can test the serialization from the console with this:
```ruby
ActiveModel::Serializer::Adapter.create(ModelSerializer.new(Model.first)).as_json
```

**Comment by cheerfulstoic** [comment]
Yep, that's something I'd like to fix.  I'm always needing to put `to_a` on associations and `all` calls...

**Comment by feedthebayer** [comment]
@cheerfulstoic, If it's not too complicated, I could take a shot at it.

**Comment by cheerfulstoic** [comment]
That would certainly be welcome!  I'm not sure how complicated it would be, but let me give you the quick tour ;)

When you call `Model.all` you get a `QueryProxy` object which allows you to start your chain.  Here's the `QueryProxy` class:

https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/active_node/query/query_proxy.rb

It's `Enumerable` via the `QueryProxyEnumerable` mixin:

https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/active_node/query/query_proxy_enumerable.rb

So that's why you can call `#to_a`, `#each`, `etc...` on it.  I'm not sure what the serializer is looking for, though.

The reason that I'm always calling `to_a` is that the results don't show up on the console until I do that.  It would be nice if we worked more like ActiveRecord in this way.

A last thing that you should be aware of is the `AssociationProxy` class:

https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/active_node/has_n.rb

You get this whenever you call an association method.  It wraps `QueryProxy` objects (which in turn wrap `Query` objects which come from the `neo4j-core`).

I'm happy to answer questions here or in our Gitter chat room: https://gitter.im/neo4jrb/neo4j

**Comment by feedthebayer** [comment]
Aha, so the serializer is using `respond_to?(:to_ary)` to determine if its an array ([see code here](https://github.com/rails-api/active_model_serializers/blob/6aba26049154712d65176708ffad55fcfe512ca0/lib/active_model/serializer.rb#L85)). If true, it uses an `ArraySerializer` that in turn runs a `ModelSerializer` on each model. 

So here's a workaround:
```ruby
render json: Model.all, serializer: ActiveModel::Serializer::ArraySerializer
```

The `ActiveRecord::Relation` that's returned from `Model.all` when using AR gets the `#to_ary` method from [ActiveRecord::Delegation](https://github.com/rails/rails/blob/f91439d848b305a9d8f83c10905e5012180ffa28/activerecord/lib/active_record/relation/delegation.rb)

It looks like we just need to define our own `#to_ary` method. Do you concur, @cheerfulstoic?

**Comment by cheerfulstoic** [comment]
Ah, really interesting, thanks!

I did some googlin' and I'm still not entirely sure I understand the difference between `to_a` and `to_ary`, but it does seems like implementing `to_ary` would help.  If I'm understanding the `ActiveRecord::Delegation` module correctly, `to_a` is called first which would return an Array and then the delegation causes `to_ary` to be called on the resulting Array.  It seems like that [returns self](http://ruby-doc.org/core-2.2.2/Array.html#method-i-to_ary), which is a bit weird.  But whatever ;)

I feel like there's a lot to be learned from that module, but for now could you try implementing a `to_ary`?

Also, this is always what I think of when the word "concur" is used ;)

http://i.ytimg.com/vi/lqe-mr_zBdg/mqdefault.jpg

**Comment by feedthebayer** [comment]
Yeah, I'm having trouble understanding exactly how it works also. [In this file](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/module/delegation.rb), the `delegate` class method is added to `Module` that can be used to delegate a method to something else. In [ActiveRecord::Delgation](https://github.com/rails/rails/blob/f91439d848b305a9d8f83c10905e5012180ffa28/activerecord/lib/active_record/relation/delegation.rb#L45), it looks like `to_ary` is delegated to `to_a`. Which would make sense because using AR, `Model.all == Model.all.to_a == Model.all.to_ary`. I suspect that irb is calling `to_ary` on any output if it responds to it because `Model.all.class == Model::ActiveRecord_Relation < ActiveRecord::Relation`, yet `Model.all.to_ary.class == Model.all.to_a.class == Array`.

So, maybe we just need to add `delegate :to_ary, to: :to_a`. Should I try adding `delegate` or `def to_ary` in `query_proxy.rb`?

**Comment by cheerfulstoic** [comment]
Yeah, try the `delegate` first to see if that works! ;p
