### ISSUE TITLE
Documentation for avaliable property types of ActiveNode

### ISSUE THREAD

**Issue by StaymanHou** [neo4jrb/neo4j#752]
I've been searching for a list of available ActiveNode property types for a while, but have not found one yet.

Could someone please paste a link here for me?

Thanks

**Comment by subvertallchris** [comment]
Our types are inherited from `active_attr`, you can see those converters at https://github.com/neo4jrb/active_attr/tree/master/lib/active_attr/typecasting. Additionally, a few others are handled by our [TypeConverters](https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/shared/type_converters.rb) module.

All together, they are:

* Boolean
* DateTime
* Date
* Float
* Integer
* String
* Time (this is currently converted to DateTime by our module but I'd like to fix that in the upcoming release)

You can also omit the `type` completely and the gem will attempt to save the property to the database as is, which may have unintended consequences but is perfectly safe for Int and String. When possible, you shouldn't declare a `type` because there is a performance hit.

You can define a custom type serializer as demonstrated at `https://github.com/neo4jrb/neo4j/blob/master/spec/unit/shared/property_spec.rb#L66`, though this may go through a little refactoring soon. Additionally, you can use the `serialize` class method to automatically convert a property to/from JSON or YAML as described at https://github.com/neo4jrb/neo4j/wiki/Neo4j%3A%3AActiveNode#property-serialization.

**Comment by subvertallchris** [comment]
Added this to https://github.com/neo4jrb/neo4j/wiki/Neo4j::ActiveNode#property-types. I'm going to see about adding it to the [new documentation](neo4jrb.readthedocs.org/en/latest/) now...

**Comment by StaymanHou** [comment]
Awesome. Thank you very much.
