### ISSUE TITLE
Model Inheritance

### ISSUE THREAD

**Issue by jamilabreu** [neo4jrb/neo4j#763]
A School model inherits from Community, and communities can be part_of other communities:
```
class School < Community
end

class Community
  include Neo4j::ActiveNode
  has_many :out, :part_of, model_class: Community
end
```
The below code only creates the relationship correctly if school.rb explicitly includes  ```has_many :out, :part_of, model_class: Community```
```
School.create(name: name, part_of: [ivy_league])
```
like this:

```
class School < Community
  has_many :out, :part_of, model_class: Community
end
```

**Comment by subvertallchris** [comment]
This is definitely due to the code I introduced to tweak what Brian added earlier. You take a small performance hit when you mix declared properties and association names, so my PR tried to identify nodes that are not being initialized with known association names. It needs to initialize the variable when inherited. Lemme see if I can do this quickly but if not, I can take care of it in the morning.

**Comment by subvertallchris** [comment]
Will merge in the morning if all passes.

**Comment by jamilabreu** [comment]
Cool :smile: So for best performance would you recommend not mixing properties and associations? Something like:
```
school = School.create(name: name)
school.part_of << ivy_league
```

**Comment by subvertallchris** [comment]
Yes, definitely. When you mix associations and node properties, not only do you take a performance hit when it splits the one params hash into separate hashes, but it uses the `=` operator to create relationships. This is an n+1 query: it wipes out existing relationships, then it creates new ones. It's a fast process since it doesn't return anything from the DB and the query itself is very efficient, but it's still slower than `<<`.

**Comment by subvertallchris** [comment]
This is merged in, fixed now. Made me realize there are probably a few other bugs related to inheritance that I'm going to check now.

**Comment by jamilabreu** [comment]
Working on this end :+1: thanks for the tip, btw! I'll keep poking around, see if I find anything

**Comment by jamilabreu** [comment]
@subvertallchris: Came across another potential inheritance bug:

```
class Person
  include Neo4j::ActiveNode
  has_many :out, :communities, type: "PART_OF"
  has_many :out, :schools
end

class Community
  include Neo4j::ActiveNode
  has_many :out, :communities, type: "PART_OF"
end

class School < Community
end
```
Adding a person to a school via a form:

```
= form_for current_person do |f|
  = f.collection_select :schools, School.all, :id, :name, { prompt: true, selected: current_person.schools.map(&:id) }
```

correctly adds the selected schools to ```current_person.schools```, but ```current_person.communities``` returns an empty array

**Comment by subvertallchris** [comment]
Could you message me in the Gitter room? I have so many questions. gitter.im/neo4jrb/neo4j
