### ISSUE TITLE
Some rake tasks

### ISSUE THREAD

**Issue by dpisarewski** [neo4jrb/neo4j#793]
I add these rake tasks into every neo4j project:

```ruby
namespace :db do
  task seed: :environment do
    seed_file = File.join('db/seeds.rb')
    load(seed_file) if File.exist?(seed_file)
  end

  task clear: :environment do
    Neo4j::Session.current.query('MATCH (n) OPTIONAL MATCH (n)-[r]-() DELETE n,r')
  end
end
```

Does it make sense to include them into the gem?

**Comment by cheerfulstoic** [comment]
Yeah, definitely!  We've already got a `neo4j` namespace for our rake tasks, so it might be good to use that.

The one thing I would say about clearing the database is that if you load data and run that cypher query over and over again Neo4j will become less performant.  I think if you restart Neo4j after you do it it does some cleanup work, but sometimes I've gone so far as to do a `rake neo4j:stop && rm -rf db/neo4j/development/data/graph.db && rake neo4j:start`, so that might be a fool-proof way to do it.  I would also add in some sort of confirmation prompt on both of those tasks

**Comment by dpisarewski** [comment]
So, do you recommend using the `rake neo4j:yes_i_am_sure` task to clear the db?

**Comment by dpisarewski** [comment]
I guess, I would also need this `clear` task when using grapheneDB.

**Comment by cheerfulstoic** [comment]
Yes, good point.  I'm not sure I knew / remembered about that task.  I think it's good to have both, though rather than having the names have something like `_yes_i_am_sure` they should have STDIN prompts to verify because it's easy enough to `ctrl-r` the wrong thing

**Comment by cheerfulstoic** [comment]
Also it looks like GraphineDB has an "Empty database" tool in their Admin UI

**Comment by jessmartin** [comment]
@dpisarewski I believe these tasks have been moved to https://github.com/neo4jrb/neo4j-rake_tasks if you are still interested in adding them to the project.

**Comment by cheerfulstoic** [comment]
It's true!  I think @framallo was talking about putting in a `seed` task.

I believe there's also been a desire for a `backup` task.  This might need to be different between community / enterprise.

I also started working a while ago on a task that would upgrade the version of Neo4j in-place.

I'm going to create an issue in `neo4j-rake_tasks` to replace this one.  Thanks @jessmartin
