### ISSUE TITLE
Connection refused on 'rails generate' in tutorial

### ISSUE THREAD

**Issue by dpipkin** [neo4jrb/neo4j#805]
I've tried to do the __getting started__ tutorial on a couple different machines and I haven't been able to make it past this error:
```
dpipkin@CORP-WEB01:~/neo_blog$ rails generate scaffold User name:string email:string
/usr/local/rvm/gems/ruby-2.1.2/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:641:in `rescue in connection_for'
 connection refused: localhost:7474 (Faraday::ConnectionFailed)
````

I don't think my neo4j server is starting up but I don't know where the logs are to find out.

**Comment by subvertallchris** [comment]
That does suggest your server isn't started. What commands did you run prior to trying to build your scaffold?

**Comment by cheerfulstoic** [comment]
Also are you able to go to `http://localhost:7474` in your browser?

**Comment by dpipkin** [comment]
I ran the commands listed here:
https://github.com/neo4jrb/neo4j/wiki/Neo4j-v3-Setup
specifically:
1) rails new neo_blog -m http://neo4jrb.io/neo4j/neo4j.rb -O
2)  cd neo_blog
3) rake neo4j:install[community-2.1.6]
4) rake neo4j:start
5) rails generate scaffold User name:string email:string

http requests are also refused.

**Comment by cheerfulstoic** [comment]
I just realized that the wiki is a bit out of date on the latest neo4j version.  The latest is 2.2.1 (wiki is updated now).

I'm curious as to the output of the tasks to know if any of them failed.  Maybe try removing the current database (assuming you don't have anything important there yet) and install 2.2.1 like this:

First make sure the database is stopped (it's not responding, so this is probably done already, but it doesn't hurt):

    rake neo4j:stop

Then you can remove the database (obviously be careful with this command to get the right directory):

    rm -rf ./db/neo4j/development

And then install 2.2.1:

    rake neo4j:install[community-2.2.1]

And start it:

    rake neo4j:start

If that doesn't work could you share the output of the commands?  I'm also realizing that there was a bug in the current version where the output of starting the server wasn't being displayed.  This is going to be fixed in 5.0 (release candidate coming tomorrow).  For now if it doesn't work you can try this to start the server:

    ./db/neo4j/development/bin/neo4j start

Hopefully that will give you good output, but if not I would look at this log file:

    ./db/neo4j/development/data/graph.db/messages.log

**Comment by dpipkin** [comment]
So I wasn't able to get it but `./db/neo4j/development/bin/neo4j start` gave me an error message :smiley:
It looks like I was having java problems on all of my machines. I'm going to update java and see what happens.

**Comment by dpipkin** [comment]
So, I got the server up and running, but now I'm having a different problem:
```
dpipkin@CORP-WEB01:~/neo_blog$ rails generate scaffold User name:string email:string
/usr/local/rvm/gems/ruby-2.1.2/gems/neo4j-core-4.0.7/lib/neo4j-server/resource.rb:33:in `handle_response_error':
Expected response code 200 Error for request http://localhost:7474/db/data/, 401, 401 (Neo4j::Server::Resource::ServerException)
```

Should I close this issue and start a new one for that?

**Comment by cheerfulstoic** [comment]
Ah, yes, starting with 2.2.0 you need a username and password.  By default this is `neo4j` / `neo4j`, though if you browse to `http://localhost:7474` is will ask you to enter a new one after you log in.

See this for the rails configuration:

https://github.com/neo4jrb/neo4j/wiki/Neo4j-v3-Setup#usage-with-a-remote-server

I'll close this issue, but feel free to open a new one if that doesn't help
