### ISSUE TITLE
Neo4j ruby gem intro screencast (NonPersistedNodeError)

### ISSUE THREAD

**Issue by nskostas** [neo4jrb/neo4j#864]
Hi, 

I'm trying to follow the tutorial of the introductory video([Neo4j ruby gem intro screencast](https://www.youtube.com/watch?v=bDjbqRL9HcM)), but I'm receiving the following error.

```
Neo4j::ActiveNode::HasN::NonPersistedNodeError in CommentsController#create
Unable to create relationship with non-persisted nodes
```
And, highlighting the following line of code:

```
 @comment = Comment.new(comment_params)
```

I have added the :post in the comment_params.

Any ideas, what might be wrong?

Thanks,
Kostas.

**Comment by cheerfulstoic** [comment]
@subvertallchris I know you were working on making something like this possible, but this is was possible when 3.0 was out because it was in my screencast.  Did we lose this ability?

See https://www.youtube.com/watch?v=bDjbqRL9HcM aronud 6:23

Getting rid of the call to `#new` and moving the arguments down to change the `save` to a `create` could help for now.  What do your `params` look like?

**Comment by subvertallchris** [comment]
Hmm... I know it does a check for a key in the init params that matches a declared association. I don't think it will autosave right now unless a config option is set. In `application.rb` or any environment rb file, use `Neo4j::Config[:autosave_on_assignment] = true`. Dieter added this a month or two ago and my forthcoming PR will make it a bit easier.

**Comment by nskostas** [comment]
Hi, 
thanks for your responses.
Setting ```Neo4j::Config[:autosave_on_assignment] = true``` in ```applicaton.rb``` fixed it.

My ```params``` were 
```{"utf8"=>"✓","authenticity_token"=>"nbc5AbgDSLmbt0Rh2FjYfQxuq8/N8jbNtfwPr28cSC+VUjK9YHZYWqx5e5LyZe7uNU8f2msFisLwaT+pgLDn3w==", "comment"=>{"body"=>"comment body", "post"=>"b4a6dd87-cb67-46fb-b26a-147065fce038"},  "commit"=>"Create Comment"}```

**Comment by cheerfulstoic** [comment]
Interesting, so maybe this behavior was there but got set to be opt-in at some point.  Unfortunately that was in the dark days when our `CHANGELOG` wasn't being very closely maintained ;)

Unfortunately for some reason I'm having trouble replying to your comment on YouTube.  Could you provide a link back to here so that people with this issue can find it?

**Comment by nskostas** [comment]
Sure, I just did it. Is it possible for this setting to be added to the wiki, because it is not mentioned anywhere.

**Comment by cheerfulstoic** [comment]
The wiki is actually becoming the old documentation.  We're trying to get everything over to:

http://neo4jrb.readthedocs.org/

This documentation is generated from the `docs` directory in this repository.  I made a pull request for this:

https://github.com/neo4jrb/neo4j/pull/868

The change to `docs/Configuration.rst` is the important thing.  Other suggestions are welcome before merging
