### ISSUE TITLE
Property :created_at is not set unless explicitely creating a relationship

### ISSUE THREAD

**Issue by dapicester** [neo4jrb/neo4j#893]
Hi,

As you can see from the following code:
```ruby

require 'neo4j'

Neo4j::Session.current || Neo4j::Session.open(:server_db)

class Person
  include Neo4j::ActiveNode
  property :name
  index :name
  has_many :out, :posts, rel_class: :WritePost
end

class Post
  include Neo4j::ActiveNode
  property :text
  index :text
  has_one :in, :user, origin: :posts
end

class WritePost
  include Neo4j::ActiveRel
  from_class :Person
  to_class :Post
  type :writes

  property :created_at
end

me = Person.find_or_create_by name: 'me'
post = Post.find_or_create_by text: 'hello world'

me.posts << [post]
puts me.posts.rels.last.inspect #<WritePost created_at: nil>

WritePost.create from_node: me, to_node: post
puts me.posts.rels.last.inspect #<WritePost created_at: Fri, 31 Jul 2015 08:19:29 +0000>
```
the property `created_at` is not set when implicitely creating a relationship using the `<<` operator.

I am not sure if this is by design or not.

**Comment by cheerfulstoic** [comment]
Currently when you create via an association your ActiveRel model isn't involved.  @subvertallchris and I were just talked a couple of days ago about potentially doing this though.  What do you this Chris?

**Comment by subvertallchris** [comment]
That is correct. You have to explicitly create relationships using your
ActiveRel class to take advantage of the timestamps, callbacks, and
validations. When using << with an association, it only refers to the rel
class for some basic info about type and model class requirements.

I'm still on the fence about changing this, only because you can do some
things with << that you can't do with ActiveRel 'create'. I might have an
idea about how we could let the basic association process borrow behavior
from the rel class, though, so maybe we can get the best of both worlds.

**Comment by cheerfulstoic** [comment]
I'm all for keeping the functionality that `<<` provides, but I feel like it should be a different method because the programmer should be "taking control" at that point and not just doing the default thing which does what you would expect

**Comment by dapicester** [comment]
I would suggest to follow Ruby's principle of last surprise, or at least to document the fact that something does not work as one may expect (as it happens in this issue).

**Comment by subvertallchris** [comment]
The code was changed in a recent release so `<<` would create using ActiveRel models when possible. As a result, timestamps will be set as one would expect, so I'm going to close this out.
