### ISSUE TITLE
Sometimes I need to reference my models in development mode to get things to work

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#972]
This isn't necessary in development mode for ActiveRecord and enable `eager_load` makes development no longer development-y.

**Comment by cheerfulstoic** [comment]
I think that this might have been due to me not understanding autoload_paths.  I think I understand it better now and so I'll re-open if I have a good example

**Comment by venkatd** [comment]
I can confirm that my tests lock up on my CI server unless `config.eager_load = true` in the test environment.

One suggestion is to rethink where indices get created. I'm wondering if, rather than magically creating indices upon use, it would be better suited for a rake task. Could throw in a logger.warn in there if you are running queries without indexes.

Thoughts?

**Comment by subvertallchris** [comment]
I floated this idea the other day, it really might be worth more thought.
Schema changes are so crucial but relatively infrequent once an app moves
past its infancy, an explicit migration take task really might be a good
thing.
