### ISSUE TITLE
Use numeric value as id instead of sha uuid

### ISSUE THREAD

**Issue by lareb** [neo4jrb/neo4j#980]
I am wondering if i can use id primary key instead of uuid. 

What I want
Asset.find(7) #=> Neo4j::Server::CypherResponse::ResponseError......

What exactly happening
Asset.find("39025efd-420d-4d22-84cc-013f4d9744f5") #=> 
Asset uuid: "39025efd-420d-4d22-84cc-013f4d9744f5", address: "One Churchill Place, London Borough of Tower Hamlets.", company_status_id: 1, created_at: "2015-09-29T17:18:46+05:30", deleted_at: "", description: nil, domain_id: 4, email: "contact-us@barclays1.com", g_slug: nil, is_active: true, logo_content_type: nil, logo_file_name: nil, logo_file_size: nil, logo_updated_at: nil, name: "Barclays", permalink: "39025efd-420d-4d22-84cc-013f4d9744f5-", phone_no: "+44 345 734 5345", publically_listed: true, total_employees: 20, updated_at: "2015-09-29T17:18:46+05:30">

**Comment by subvertallchris** [comment]
Sorry but that is not an option in the gem. The database's internal IDs may
be reused, so they are inappropriate for use as node primary keys. You can
use `find_by(neo_id: id)` to search based on that value.

**Comment by cheerfulstoic** [comment]
It occurs to me that you might be asking about using your own numeric IDs as a property on your nodes rather than a hash string like we generate.  It is possible to use your own IDs like this:

```ruby
    id_property :boid, on: :new_id

    def new_id
      # Some algorithm
    end
```

The trick would be incrementing IDs on your own in a way that doesn't have any race conditions.  You can make a query like this:

```ruby
Neo4j::Session.current.match('(n)').order(n: {id: :desc}).limit(1).pluck('n.numeric_id')
```

But as your database grows that query will get slower and slower.  And if you get two processes trying to create an ID at the same time you could get an error because the Neo4j constraint (which is created automatically from the `id_property`) kicks in and prevents the second create.

Also something that you might want to be aware of: https://github.com/graphaware/neo4j-uuid

I'm going to close this issue, but please feel free to re-open if you feel like we've misunderstood

**Comment by lareb** [comment]
Thanks @cheerfulstoic and @subvertallchris for the reply, but is there is a way to minimize uuid length, right now it has 26 char, can I control the max length to 8 or 10 ?

**Comment by cheerfulstoic** [comment]
Yeah, certainly!  We use the `SecureRandom` module in Ruby to generate random UUIDs, so I'd suggest that you use that.  Something like:

```ruby
require 'securerandom'
SecureRandom.hex(10)
```

With ten characters you should have 16^10 = 1,099,511,627,776 possible combinations, so you're probably pretty good ;)

Perhaps better is using something like `friendly_id`:

https://github.com/norman/friendly_id

I haven't actually used it with `ActiveNode` yet, but I've been planning on testing it with an application which I've been developing.  Regardless it should be possible to code up a simpler version yourself if it doesn't work
